### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for user_id: 459bd572-5c41-42ff-9bb0-bf13b14c6613, item_id: 62f07106-5e54-5c82-90f4-a7fcb8628d5f was not successful. status: 422, {
  "errors" : [ {
    "message" : "loan at maximum renewal number",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "28day-2renew-7daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "3efe7693-3357-4f9b-999d-a271f86019b0"
    } ],
    "overridableBlock" : {
      "name" : "renewalBlock",...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#1057]
## Backtrace

    line 242 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 103 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_by_id
    line 84 of [PROJECT_ROOT]/app/services/folio_client.rb: block in renew_items

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/99827607)

**Comment by corylown** [comment]
I think this is covered by https://github.com/sul-dlss/mylibrary/issues/1083
