### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for user_id: 3d183315-00e9-4d9d-a7ac-cd3f3a7a0c5b, item_id: da23f569-2540-59d8-ae91-b81a0fd0ff0d was not successful. status: 422, {
  "errors" : [ {
    "message" : "Items with this loan policy cannot be renewed when there is an active, pending hold request",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "1yearfixed-2renew-7daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "ad47ac4d-8305-4039-8ac4-93a69a789074"
...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#1058]
Similar to #1057. It seems like we're missing some logic around eligibility?

## Backtrace

    line 250 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 111 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_request
    line 87 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/103387334)

**Comment by corylown** [comment]
I think this is covered by https://github.com/sul-dlss/mylibrary/issues/1083
