### ISSUE TITLE
Add SASS configuration for application-specific styles (headers, fonts, etc)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#11]
@jvine to provide styles for:

- [ ] page header links
- [ ] page nav buttons
- [ ] text headers
- [ ] body text
- [ ] table headers
- [ ] responsive text sizes
- [ ] modal text
- [ ] ALL THE THINGS

**Comment by jvine** [comment]
In progress below...

### Body text and headers

From https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/stylesheets/base.scss
```
a {
  border-bottom: 1px solid transparent;
  color: $sul-link-color;
  text-decoration: none;

  &.disabled {
    color: $sul-btn-disabled-color;
    cursor: not-allowed;
    text-decoration: none;
  }
}

a:hover, a:focus, a:active  {
  @include link-styling;
}


body {
  font-family: 'Source Sans Pro', 'Arial Unicode MS', Helvetica, sans-serif;
}

h1 {
  color: $sul-h1-font-color;
  font-weight: 300;
  line-height: 1.2em;
}

h2 {
  color: $sul-h2-font-color;
  line-height: 1.2em;
}

h3 {
  color: $sul-h3-font-color;
  line-height: 1.2em;
}

h4 {
  color: $sul-h4-font-color; 
  line-height: 1.2em;
}
```

### Heading sizes
From https://github.com/sul-dlss/SearchWorks/blob/master/app/assets/stylesheets/bootstrap-variables.scss
```
// Typography
$font-size-h1: 2.323em;
$font-size-h2: 1.793em;
$font-size-h3: 1.383em;
$font-size-h4: 1.215em;
$headings-font-weight: 400;
```

### Title font
We continue to need this wretched font for diacritics in titles.
```
https://github.com/sul-dlss/SearchWorks/blob/c635c9fa121da74e4da88bfac7320305fd32bb9d/app/assets/stylesheets/searchworks-mixins.scss

@mixin h3-index-title-small-font {
  font-size: 1.138em;
  line-height: 1.4em;
}

@mixin h3-index-title-font {
  font-family: 'dejavu_sansextralight', 'Arial Unicode MS', Helvetica, sans-serif;
  font-size: $font-size-h4;
  letter-spacing: -.03em;
  line-height: 1.5em;
}
```

### Buttons
Bootstrap default size.

<img width="240" alt="button colours" src="https://user-images.githubusercontent.com/6945691/60849248-c1cf3e00-a19e-11e9-9dae-bbd13304fc43.png">

Primary:  $cardinal-red
Default:  $cloud;
Blue:  $bright-blue;
