### ISSUE TITLE
Configure -uat + -prod connection to symphony

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#121]
We have -uat and -prod set up, but we're sending a bunch of errors to Honeybadger because we're not hooked up to Symphony yet. We'll want to consult with @jgreben and @sdoljack re: which Symphony credentials to use.

**Comment by jgreben** [comment]
We set up shared_configs to connect to symphony in the following PRs:
https://github.com/sul-dlss/shared_configs/pull/976
https://github.com/sul-dlss/shared_configs/pull/977

Note that the configuration to UAT is the Symphony dev system (`symws-dev` & `morison`) so we will be able to modify back-end data without changing production.

Also note that we will need to request a new clientID from SirsiDynix for use in prod. Currently we are just re-using `SymWSTestClient`. Getting a new clientId involves making a help request to SirsiDynix. Then they will provide us with a new file to upload via the symws web client. We will have both `SymWSTestClient` and a new `SymWSProdClient` in the clilentID string.

**Comment by cbeer** [comment]
We'll want to point UAT at the prod system as soon as we're comfortable doing so, because -uat is our environment for testing production fixes.

**Comment by shelleydoljack** [comment]
I propose we use client ID `SymWSStaffClient` and associate this client ID with `Web Services Staff` in Symphony Web Services administration. The reason I think we should use the staff interface is because we log into Symphony (acquire the session token) using a "staff user" and not the patron. The value of `sd-originating-app-id` is where we could specify MyLibrary dev or MyLibrary prod (or MyAccount?).

**Comment by shelleydoljack** [comment]
I updated the shared configs for mylibrary-dev, -uat, and -prod to use the same client ID SymWSStaffClient. The PR for -dev is https://github.com/sul-dlss/shared_configs/pull/978 . I also configured symws-dev and symws-prod to map this client ID to the Web Services Staff Symphony Interface and removed the user standing map policy in Symphony that blocks circulation transactions for our logged in staff user if it's user standing is blocked (which it likely won't be).
