### ISSUE TITLE
Fix up font sizes on masthead

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#127]
![Screen Shot 2019-07-15 at 5 04 39 PM](https://user-images.githubusercontent.com/5402927/61256731-ae821c80-a722-11e9-92f9-aa63fb34e6d4.png)
![Screen Shot 2019-07-15 at 5 04 34 PM](https://user-images.githubusercontent.com/5402927/61256732-ae821c80-a722-11e9-9f34-19a68a14e4a4.png)

**Comment by camillevilla** [comment]
Closed in #128

**Comment by jkeck** [comment]
👍 thanks @camillevilla, I didn't even catch that this ticket was filled. 😅
