### ISSUE TITLE
Update checkout status values

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#131]
In order of priority:

- [x] (red/circle) Recalled
- [x] (red/circle) Recalled $amount (once fines are accruing)
- [x] (no icon) Processing claim (if patron has claimed they returned the item)
- [x] (orange/triangle) Assumed lost $amount (until it’s been paid or returned)
- [x] (orange/triangle) Overdue $amount (once fines are accruing)
- [x] (orange/triangle) Overdue (no fines accruing yet) 
- ~~(no icon) Reserve item (if it is one)~~       
- [x] (no icon) Blank

**Comment by cbeer** [comment]
@saseestone: how do we know if an item is a reserve item?

**Comment by saseestone** [comment]
Just had a conversation with Jennifer about this and we agree that the most interesting thing about this checkout type is not that it's a reserve item...but that it's a short-term loan.  That will be evident from the other details we already have - especially the due date/time.  

So the decision is to not add this to the Checkout detail for now.  We can evaluate later (after user feedback and analytics) if we need it, and then add it in in a future cycle.

I've stricken it from the labels and content doc and put in a note there.

**Comment by cbeer** [comment]
@jvine / @saseestone: what amount should appear for the `Assumed lost $$$`? It seems like our fixture item has an overdue fee, and there are 2 separate fines for the item.

**Comment by jvine** [comment]
After discussion with Sarah:   The amount to show on the Checkouts tab is the overdue fee. The lost item charge(s) are separate, and appear on the Fines tab. At some point we might consider connecting them in some way, but for now: parity.

(Once the user pays the lost item charges, the item is "returned" and the accruing overdue fine is automatically billed and shown on the Fines tab; at that point, the item no longer shows in Checkouts.)
