### ISSUE TITLE
Distinguish between hourly loans and regular checkouts 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#142]
It looks like this information is encoded in the loanPeriod policy, e.g.

```ruby
{"resource"=>"/policy/loanPeriod",
     "key"=>"3H",
     "fields"=>
      {"policyNumber"=>50,
       "description"=>"0",
       "displayName"=>"3H",
       "periodType"=>{"resource"=>"/policy/periodType", "key"=>"HOURLY"},
       "periodCount"=>3,
       "dayInWeek"=>{"resource"=>"/policy/weekdays", "key"=>"SUNDAY"},
       "timeDue"=>nil,
       "dueDateList"=>[]}}
```

The periodTypes could be:

`["DATELIST", "INDEFINITE", "WEEKLY", "DAILY", "MINUTES", "HOURLY"]`

If the PeriodType is HOURLY or MINUTES, show the due date time instead of just the date:

<img width="383" alt="Screen Shot 2019-07-17 at 13 16 19" src="https://user-images.githubusercontent.com/111218/61408549-21aba000-a895-11e9-89e4-b923349e950a.png">

**Comment by saseestone** [comment]
Just FYI: we only use "DATELIST", "DAILY" and "HOURLY"

DATELIST = A specific date set in the loan period policy.  It's the mechanism to assign the annual due date (June 30) and the quarterly due dates.

**Comment by jkeck** [comment]
Does this manifest itself in the UI somewhere that would need to reflect this identification?

**Comment by cbeer** [comment]
Hourly checkouts display the due date as `Month day, YYYY hh:mm`; I don't think DATELIST vs DAILY is an important distinction for us.

**Comment by cbeer** [comment]
(and I've snuck that distinction into the ticket description)
