### ISSUE TITLE
Add checkout quota to fee borrower patron info

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#144]
Split out from #53 

It looks like we can get this information from the `userProfile` policy `chargeLimit` field

**Comment by jkeck** [comment]
@saseestone is there a particular threshold that we should not show this information if we reach it?  It looks like 25000 is a regular number that is returned and I wasn't sure if we wanted to put that number out there or not.  Perhaps this is a user-type sort of thing, but this may still be served well by a threshold sort of thing (e.g. if it's more than we allow typical users that we would show this information, then we don't show it).

**Comment by saseestone** [comment]
So I'm guessing that we've used "25000" to really mean "No limit" in the database.  If that's the case, it's probably best to show a translation like "unlimited".  Possible?

There are only a few user types that have a real charge limit with a number in this field, so most users would see the translation.  @jvine do you have an opinion on what the translation is?

**Comment by jvine** [comment]
We only show this information for fee borrowers, not SUNet ID or proxy patrons. I only want it visible when there's a real limitation. Is there any type of fee borrower that will have unlimited borrowing privileges?

**Comment by jkeck** [comment]
Okay, it seems like we should set the threshold to 25000 and consider that as being no limit (and not display the data at all).

**Comment by shelleydoljack** [comment]
I checked the WorkFlows help for my own sanity:

>Charge Limit
>The Charge Limit attribute is the maximum number of items any user may have checked out at one time. If the Charge Limit is UNLIMITED, a user may have up to 25,000 items checked out simultaneously. Unlike the Overdue and Bill Thresholds, the user’s status is not updated automatically at the workstation when the Charge Limit is met. When the user’s Charge Limit is reached, regardless of the delinquency status, only an operator override allows that user to check out items. Use the Minimum/Maximum gadget to select a limit between 0-24,999, or select UNLIMITED.
>Note: The Charge Limit is not linked to the user status. Even when the Charge Limit has been reached and an override is required, and the Update User Delinquency Status report has been run, the user status does not change.

There is also a charges allowed field, but this seems to mean overall charges before privileges expire:
>Charges Allowed
>When a user is added to the system or has his privilege extended, the User Profile policy determines how many charges the user can make before their privilege expires. Use the Minimum/Maximum gadget to select a number between 0-24,999, or select UNLIMITED.
>For example, if the user’s profile says she is allowed a total of five charges, then after the user checked out her fifth item, her privilege must be renewed before she can charge out more items. Each time her privilege is renewed she may charge out five more items.

**Comment by saseestone** [comment]
@jvine - All Fee Borrowers have a Charge Limit.  Either 25 or 6 items.

@shelleydoljack - we don't use the "Charges Allowed" policy here at Stanford.  (It just doesn't work well in a multi-library system with a LOT of staff & student workers.)  Memory is that it was added to the policies when SD went global and needed to meet the needs of UK libraries.

**Comment by cbeer** [comment]
@jkeck that sounds right to me; from the docs @shelleydoljack posted, 25000 is the Symphony equivalent of unlimited.
