### ISSUE TITLE
Analysis: Can we get a list of a sponsor's personal research group checkouts?

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#161]

**Comment by camillevilla** [comment]
This afternoon's pairing session yielded the following insights:

When trying to find a  `describe group` only gives us a memberlist. We then look up each of those patrons and grab their circ records, holds, etc. We cannot distinguish between a faculty member's personal checkouts and their research group checkouts via Symphony webservices.

This is a blocker for us moving forward with #159

Possible next steps:
- @shelleydoljack reaching out to SirsiDynix customer support
- Analysis of current usage: Are faculty actually checking out books to their research group?
- If this feature isn't heavily used, we could change policy to issuing proxy cards for faculty members
- We could do something weird and connect to the OracleDB and look at the usergroup key in charges (personal checkouts are assigned negative keys, research group checkouts are assigned positive keys that

**Comment by shelleydoljack** [comment]
We tried a call using the legacy web services and the response also does not tell us if the checkout is for the group or for the individual. This is the legacy call: 
```
curl -i -X GET \
   -H "x-sirs-clientID:DS_CLIENT" \
   -H "x-sirs-sessionToken:70a79cd8-a2c9-4f14-8e60-230769413334" \
 'http://symws-dev.stanford.edu/symws/rest/patron/lookupPatronInfo?userID=FACULTY2&iincludePatronInfo=true&includePatronCirculationInfo=true&allowedDisplayGroupFees=true&includeFeeInfo=ALL_FEES_AND_PAYMENTS&includePatronCheckoutInfo=ALL&allowedDisplayGroupFees=true&includeUserGroupInfo=true&allowedDisplayGroupCheckouts=true&allowedDisplayGroupHolds=true'
```

**Comment by jvine** [comment]
On review with Sarah, and lacking more detailed information on usage, and not wanting to change business practices to support a UI choice, we would like to stick with this basic distinction for both the faculty sponsor and the proxies:

Tab A = Everything that I (logged in user) have done
Tab B = Everything that everyone else in the group except me has done

The most common pattern is that faculty do not share their checkouts with their research group. Checkouts for the group are primarily done by the proxies. If the faculty chooses to share an item with the group, the proxies will see it on their Tab B.

**Comment by cbeer** [comment]
> Now wondering if we can include the Faculty's shared checkouts in the proxy's tab B? I think part of the issue is that we may not know from web services which are the shared checkouts.

Exactly; so far in our explore it seems like we don't have anything that distinguishes personal vs group checkouts. For the sponsors this isn't a problem, but may be problematic to show proxies the checkouts the faculty has done on behalf of the group.

**Comment by jvine** [comment]
I think we could err on the side of just keeping the faculty's checkouts private for now. If the faculty says "share" (not the common use case) and we don't actually share... we'll learn how how it affects the group.

**Comment by cbeer** [comment]
Yep -- I think @saseestone is going to run the numbers and see how much the feature is used currently.

**Comment by camillevilla** [comment]
While @saseestone's analysis was unable to yield specific numbers, we have confirmed that faculty do indeed check items out to their research group. However, by default policy, proxy borrowers cannot see the faculty member's research group checkouts. 

We'll be following the approach outlined by @jvine in the comment above and in #165 .
https://github.com/sul-dlss/mylibrary/issues/161#issuecomment-512610661 
https://github.com/sul-dlss/mylibrary/issues/165#issuecomment-513308288

Implementation of this feature is happening in #177.
