### ISSUE TITLE
Where should a faculty's checkouts to the group be displayed?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#165]
See comment on #161 - 

1. When the faculty sponsor is the current user:
Faculty's checkouts/requests - regardless of whether they choose to share them with their proxy group - will be shown on the Faculty's tab, but not on the group tab.

2. When a proxy member is the current user:
Faculty's checkouts/requests shared with the group at time of checkout/request should be shown on the Group tab. 

Questions about whether 2 is possible.

**Comment by jvine** [comment]
We've determined that 2 is not possible right now. We will proceed with not showing any Faculty checkouts to proxy group members, and assess how this actually affects proxy users. Possible future work.
