### ISSUE TITLE
Layout and HTML/accessibility fixes for Contact dialog

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#167]
- [x] remove ` offset-sm-1` from `<div class="modal-header">` and `<div class="modal-body">`
- [x] change the `<h3>` to `<h2>`
- [x] change the "Reporting from:" label to "Source:" (easier to format)
- [x] set the number of rows for the `<textarea>` to 10 (from 15)
- [x] add `<label for="message" class="sr-only">Your message:</label>` immediately above the `<textarea>`
- [x] make the text info at the top into a `<dl>` outside of the <div> it's currently in, with a 2/10 column layout
- [x] make the col width for the remaining sections `col-12`

This is the outcome of the last 2 checkboxes:
```
<form>
   <dl class="row">
      <dt class="col-2">Label:</dt> 
      <dd class="col-10">Value</dd>
   </dl>
   <div class="row">
      <div class="col-12 mt-3 mb-3">
         <textarea>
      </div>
      <div class="col-12">
         <button>...
      </div>
   </div>
</form>
```

### Before
<img width="517" alt="contact form before" src="https://user-images.githubusercontent.com/6945691/61417466-0b5d0e80-a8ac-11e9-93b5-57039fb42dbb.png">

### After
<img width="510" alt="contact form after" src="https://user-images.githubusercontent.com/6945691/61417483-14e67680-a8ac-11e9-87c4-2359a5446546.png">

**Comment by mejackreed** [comment]
@jvine I think the "reporting from" text is included from the same partial from the feedback form. Should it be changed there too, or only here?

**Comment by jvine** [comment]
Ugh. It would be okay to change it in Feedback as well, but then we'll have variance in the Feedback form between My Library and other apps. I guess that's fine.

**Comment by mejackreed** [comment]
We could have it different, just want to clarify the use here

**Comment by jvine** [comment]
Let's have it different.

**Comment by jvine** [comment]
Won't adding the `<dl>` structure around the content affect the partial as well?

**Comment by mejackreed** [comment]
Yep, I think we will just use our own thing here.
