### ISSUE TITLE
Copy over the Searchworks library/location code -> SUL library short name data

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#17]
Short library names will be used in various places in the UI, e.g.
<img width="162" alt="Screen Shot 2019-07-08 at 15 44 13" src="https://user-images.githubusercontent.com/111218/60847354-3f8f4b80-a197-11e9-8f54-ced60d37e32e.png">

So, get the data ready to consume in a way similar to Searchworks (or Requests, but we particularly want the short names, not the long ones).

**Comment by jvine** [comment]
For now, we'll need to use the library translations in https://github.com/sul-dlss/SearchWorks/blob/c635c9fa121da74e4da88bfac7320305fd32bb9d/lib/constants.rb

Some shorter names/acronyms are prohibited by the website style guide. Will have to adjust this layout to account for reality.
<img width="374" alt="Screen Shot 2019-07-08 at 5 01 01 PM" src="https://user-images.githubusercontent.com/6945691/60849960-04464a00-a1a2-11e9-80f2-2c15f1ee1a80.png">
