### ISSUE TITLE
Add workflow for paying fines

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#170]
Triggered by a button on the fines page:
<img width="287" alt="Screen Shot 2019-07-18 at 07 40 21" src="https://user-images.githubusercontent.com/111218/61466752-52401800-a92f-11e9-9fe1-2069853fda13.png">

Triggers a confirmation modal:
<img width="450" alt="Screen Shot 2019-07-18 at 07 40 38" src="https://user-images.githubusercontent.com/111218/61466773-5a985300-a92f-11e9-9dae-572bef0a13b0.png">

** magic happens **
- POST to the SecureAcceptance Payment Form using: 
  - url: `http://{symphony_host}/secureacceptance/payment_form.php`
  - params: `reason, session_id (can be any session_id), group ('G' if a group payment), amount, billseq, user (barcode)`
-  User gets taken to the CyberSource payment form via secureacceptance workflow:
  -`payment_form.php` includes secureacceptance profile's `access_key` and "signed fields"; passes them along to:
  -`payment_confirmation.php` which includes the secureacceptance profile's secret key, verifies the signed fields are included in the post
  -`POST to https://secureacceptance.cybersource.com/pay` with `access_key`, `secret_key`, and signed fields.
- User interacts with CyberSource payment form. We never handle the person's credit/debit card or PII associated with card.
- After successful transaction they are presented with a receipt and a button that is a link back to `https://mylibrary-dev.stanford.edu/fines`.

The user gets sent back to our site and we show a flash message:
 
<img width="436" alt="Screen Shot 2019-07-18 at 07 41 03" src="https://user-images.githubusercontent.com/111218/61466813-6b48c900-a92f-11e9-92cf-9710bf1c75c1.png">

- Note, it may not be possible to display the above "success" flash message, or a corresponding "fail" message at this point, unless the request referrer from CyberSource contains that information. The button to return from CyberSource to the mylibrary app is a single configuration that applies to both the receipt page (on success) and the canceled page (on failure). The best we may be able to do is say something like:

`You will receive a receipt by email. A successful payment may take up to 5 minutes to appear in your payment history.`

**Comment by cbeer** [comment]
@jgreben: could you please fill out the ** magic happens ** section with information about how to call the symphony PHP script?

**Comment by jgreben** [comment]
@jvine can you review the note in the comment above about the flash message and suggest a design, given that we are likely unable to know whether the payment was actually successful?

**Comment by jvine** [comment]
> Also, do we want the redirect back to mylibrary button to go to the Summaries page or directly to the Fines tab?

The Fines tab.

**Comment by jgreben** [comment]
@jvine When a person cancels a payment from CyberSource it will take them back to mylibrary with a flash message. Currently:
`Payment canceled. No payment was made for the payable amount.`

![Screen Shot 2019-07-25 at 11 01 38 AM](https://user-images.githubusercontent.com/3093850/61897301-a026c400-aecb-11e9-909b-4b8472dc7b5e.png)


Please advise as to wording.

**Comment by jvine** [comment]
If this wording question is still outstanding... 

`<span class="font-weight-bold">Payment canceled.</span> No payment was made &mdash; your payable balance remains unchanged.`

<img width="955" alt="Screen Shot 2019-07-29 at 2 56 10 PM" src="https://user-images.githubusercontent.com/6945691/62085685-059eeb80-b211-11e9-8d2a-ad3b8ce6c6c0.png">

**Comment by jvine** [comment]
@jgreben what's the status of this:

> @jvine can you review the note in the comment above about the flash message and suggest a design, given that we are likely unable to know whether the payment was actually successful?

I thought that you had found a way to capture the success/fail if we didn't route them through a receipt page. Is this still an open question?

**Comment by jgreben** [comment]
@jvine, we do have a way to check the success/fail. We just need to change the error flash message as shown 👆
