### ISSUE TITLE
Debug connection problem between uat and symws-prod

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#173]
`[mylibrary/uat] OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)`

## Backtrace

    line 88 of [PROJECT_ROOT]/app/services/symphony_client.rb: request
    line 38 of [PROJECT_ROOT]/app/services/symphony_client.rb: session_token
    line 12 of [PROJECT_ROOT]/app/services/symphony_client.rb: ping

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/52371588)

**Comment by cbeer** [comment]
This looks very familiar; maybe we applied a fix only to symws-dev

**Comment by tallenaz** [comment]
Fix is applied to symws-prod.
