### ISSUE TITLE
Pick an approach for embedding icons

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#19]
Design mocks currently use icons from material design, but they could be anything.

Presumably we also need the item type icons from Searchworks?

## General
- [ ] external link icon
- [ ] expand/collapse (maybe just `+`/`-`?)
- [ ] dropdown caret

## Nav
- [x] summary
- [x] checkouts
- [x] requests
- [x] fines

## Badges
- [ ] green check
- [ ] yellow/orange warning triangle (e.g. Overdue)
- [ ] red warning circle (e.g. Recalled)

## Icon buttons
- [ ] Credit card
- [ ] Renew
- [ ] calendar (e.g. change requested date)
- [ ] cancel request
- [ ] telephone
- [ ] email (e.g. contact access services)

## Item types
- ??
<img width="328" alt="Screen Shot 2019-07-09 at 1 13 51 PM" src="https://user-images.githubusercontent.com/5402927/60919800-7d4dac00-a24b-11e9-995f-883681ec797b.png">
<img width="303" alt="Screen Shot 2019-07-09 at 1 13 28 PM" src="https://user-images.githubusercontent.com/5402927/60919804-7d4dac00-a24b-11e9-97af-123a8b569103.png">

**Comment by mejackreed** [comment]
A few thoughts.. 

This assumes that we have multiple icon sources that we will be pulling from (SearchWorks Icons, Material Design, etc). The best way to integrate might just to be use SVG for the icons everwhere. And if we do adopt react, then we could use existing patterns to do that integration. I might want to wait just a bit longer to see which way we go before trying to integrate just yet.

**Comment by jvine** [comment]
### General
Image | Source | Code
--- | --- | ---
<img width="26" alt="external link" src="https://user-images.githubusercontent.com/6945691/61007200-14d0fe80-a321-11e9-9243-dd827d812a0b.png">  | sharp-open_in_new-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M19 19H5V5h7V3H3v18h18v-9h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/></svg>`
<img width="25" alt="expand" src="https://user-images.githubusercontent.com/6945691/61007210-1bf80c80-a321-11e9-82eb-da55fcdf71a4.png">  | sharp-add-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>`
<img width="22" alt="collapse" src="https://user-images.githubusercontent.com/6945691/61007221-21555700-a321-11e9-9817-8b0d7e3e606b.png">  | sharp-remove-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M19 13H5v-2h14v2z"/></svg>`

### Nav
Image | Source | Code
--- | --- | ---
<img width="22" alt="summary" src="https://user-images.githubusercontent.com/6945691/61007639-27980300-a322-11e9-9be0-b4fde53ede5e.png">  | sharp-person-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>`
<img width="24" alt="checkouts" src="https://user-images.githubusercontent.com/6945691/61007686-4e563980-a322-11e9-9712-62cff5a93b72.png">  |  sharp-playlist_add_check-24px  |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M14 10H2v2h12v-2zm0-4H2v2h12V6zM2 16h8v-2H2v2zm19.5-4.5L23 13l-6.99 7-4.51-4.5L13 14l3.01 3 5.49-5.5z"/></svg>`
 <img width="25" alt="requests" src="https://user-images.githubusercontent.com/6945691/61007743-78a7f700-a322-11e9-8ca7-c9a7c6b32ca3.png"> | sharp-access_time-24px |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67z"/></svg>`
<img width="22" alt="fines" src="https://user-images.githubusercontent.com/6945691/61007776-95442f00-a322-11e9-95ec-62409bb73e72.png"> | sharp-attach_money-24px  |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M11.8 10.9c-2.27-.59-3-1.2-3-2.15 0-1.09 1.01-1.85 2.7-1.85 1.78 0 2.44.85 2.5 2.1h2.21c-.07-1.72-1.12-3.3-3.21-3.81V3h-3v2.16c-1.94.42-3.5 1.68-3.5 3.61 0 2.31 1.91 3.46 4.7 4.13 2.5.6 3 1.48 3 2.41 0 .69-.49 1.79-2.7 1.79-2.06 0-2.87-.92-2.98-2.1h-2.2c.12 2.19 1.76 3.42 3.68 3.83V21h3v-2.15c1.95-.37 3.5-1.5 3.5-3.55 0-2.84-2.43-3.81-4.7-4.4z"/></svg>`


### Badges
Image | Source | Code
--- | --- | ---
<img width="28" alt="ok" src="https://user-images.githubusercontent.com/6945691/61007875-d9373400-a322-11e9-8ff1-fe6fa5425590.png"> | sharp-check_circle-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/></svg>`
<img width="32" alt="overdue" src="https://user-images.githubusercontent.com/6945691/61007919-f4a23f00-a322-11e9-9238-bcd1010657ed.png"> | sharp-warning-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/></svg>`
<img width="26" alt="block" src="https://user-images.githubusercontent.com/6945691/61007969-1bf90c00-a323-11e9-8c7f-9d7862cce998.png"> | sharp-error-24px | `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>`


### Icon buttons
Image | Source | Code
--- | --- | ---
<img width="28" alt="payment" src="https://user-images.githubusercontent.com/6945691/61008031-45b23300-a323-11e9-9215-649b38e762e7.png">  | sharp-payment-24px |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M22 4H2v16h20V4zm-2 14H4v-6h16v6zm0-10H4V6h16v2z"/></svg>`
<img width="24" alt="renew" src="https://user-images.githubusercontent.com/6945691/61008075-6da19680-a323-11e9-8d22-744308b72ae0.png">  | custom |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24,0H0V24H24Z" fill="none"/><path d="M10,3a9,9,0,0,1,9,9h3l-4,3.99L14,12h3a7.034,7.034,0,1,0-2.06,4.94l1.42,1.42A9,9,0,1,1,10,3Zm1,5v5L6.75,15.52l-.77-1.28L9.5,12.15V8Z" transform="translate(1)"/></svg>`
<img width="25" alt="calendar" src="https://user-images.githubusercontent.com/6945691/61008122-988bea80-a323-11e9-9c61-8b5a861f0a4c.png">  | sharp-date_range-24px |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M9 11H7v2h2v-2zm4 0h-2v2h2v-2zm4 0h-2v2h2v-2zm4-7h-3V2h-2v2H8V2H6v2H3v18h18V4zm-2 16H5V9h14v11z"/></svg>`
<img width="26" alt="cancel" src="https://user-images.githubusercontent.com/6945691/61008183-bb1e0380-a323-11e9-809b-4616cc3c3616.png">  | outline-cancel-24px |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path opacity=".87" fill="none" d="M0 0h24v24H0V0z"/><path d="M12 2C6.47 2 2 6.47 2 12s4.47 10 10 10 10-4.47 10-10S17.53 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm3.59-13L12 10.59 8.41 7 7 8.41 10.59 12 7 15.59 8.41 17 12 13.41 15.59 17 17 15.59 13.41 12 17 8.41z"/></svg>`
<img width="24" alt="phone" src="https://user-images.githubusercontent.com/6945691/61008219-d25cf100-a323-11e9-96ed-e8119cf721b3.png">  | sharp-phone-24px  |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M21 15.46l-5.27-.61-2.52 2.52c-2.83-1.44-5.15-3.75-6.59-6.59l2.53-2.53L8.54 3H3.03C2.45 13.18 10.82 21.55 21 20.97v-5.51z"/></svg>`
<img width="27" alt="email" src="https://user-images.githubusercontent.com/6945691/61008278-f3254680-a323-11e9-81ae-42c9f243707b.png">  | sharp-email-24px  |  `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0V0z"/><path d="M22 4H2v16h20V4zm-2 4l-8 5-8-5V6l8 5 8-5v2z"/></svg>`

**Comment by mejackreed** [comment]
Based off of @jvine 's work.. I suggest we do something along the lines of: https://github.com/projectblacklight/blacklight/commit/770a56642be3e18726f50730656ff86c6d687b30
