### ISSUE TITLE
"View in SearchWorks" link needs space between icon and text

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#191]
See also #141 

The icon and text for the "View in SearchWorks" information + policy links are too close together.

<img width="162" alt="Screen Shot 2019-07-19 at 4 00 49 PM" src="https://user-images.githubusercontent.com/6945691/61569969-b7cefa00-aa3e-11e9-88ce-30b157f7b147.png">

Some icon links are using a space at the front of the link text to provide separation but that's inconsistent. Better solution IMO would to be add a margin to the SVG when it's in the context of a link.

`a .sul-icons {margin-right: .5em;}`

<img width="168" alt="Screen Shot 2019-07-19 at 4 03 40 PM" src="https://user-images.githubusercontent.com/6945691/61569983-ccab8d80-aa3e-11e9-8eab-8c67b23df671.png">

(Un-"bolding" the icon is covered in #179 )

**Comment by mejackreed** [comment]
Resolved in #197
