### ISSUE TITLE
patron info: eResource access

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#214]
Split out from #53 
- blocked until we have LDAP permissions
- This only displays for fee borrowers

**Comment by jvine** [comment]
Note that this content as designed is meant to display only for Fee borrowers logged in with a PIN. I think it's a flat statement ("you don't have it") and is meant to offset a common question to the circ desk. @saseestone can clarify if we want to do more than this for sponsored SUNet IDs.

**Comment by cbeer** [comment]
FWIW, I think the rules for sunetid users are somewhat arcane, but we should have all (most?) of that information with our new LDAP permissions.
