### ISSUE TITLE
For BARRED, try a translation of "Contact us" instead of "Blocked".

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#215]
For BARRED, I'd like to ~~try~~ use a translation of "Contact us" instead of "Blocked". (JV edited)

<img width="98" alt="Screen Shot 2019-07-17 at 11 44 18 AM" src="https://user-images.githubusercontent.com/6945691/61402581-46e5e180-a888-11e9-9fce-d88b54074846.png">

The user can clear the BLOCKED status by paying their fines. They can't do anything about BARRED _except_ contact Access Services. I'd like that to be visible in the nav, not just the summary page.

**Comment by jvine** [comment]
Not sure what the design-needed aspect is here?

**Comment by cbeer** [comment]
I wasn't sure if your "try" comment from the other ticket suggested more conversation or thought before implementation.
