### ISSUE TITLE
Styling revisit now that nav tabs have data

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#221]
Examples from 7/23:
## Longer summary value forces 4th tab to the next line
![Screen Shot 2019-07-23 at 3 41 06 PM](https://user-images.githubusercontent.com/5402927/61752735-bb75c000-ad61-11e9-944e-f011ae10fdae.png)

## Longer values sometimes force icons and copy onto separate lines
![Screen Shot 2019-07-23 at 3 40 48 PM](https://user-images.githubusercontent.com/5402927/61752736-bc0e5680-ad61-11e9-9662-f312cde0cb09.png)

**Comment by cbeer** [comment]
Could we set a min-width for the page? It seems like Firefox lets you shrink the page more than Safari does.

**Comment by jvine** [comment]
For `#mainnav .info` add
```
    font-size: .9em;
    white-space: nowrap;
```

For `.nav` add `padding-right: 0;`

For `.nav-link` change `padding: 0.5rem 1rem;` to `padding: 0.5rem 1rem;`

And then it works on iPhone 5 (320px wide)
![Screen Shot 2019-07-23 at 5 09 22 PM](https://user-images.githubusercontent.com/6945691/61755503-a9e5e580-ad6c-11e9-9624-abf3bd8547b9.png)

It's possible that a very bad borrower could have a combination of statuses that breaks on iPhone 5, but... I think it will be pretty rare (and the least of their worries).

**Comment by cbeer** [comment]
> For .nav-link change `padding: 0.5rem 1rem`; to `padding: 0.5rem 1rem;`

From trying things out, I assume this should be`padding: 0.5rem`?

**Comment by jvine** [comment]
D'oh. Yes. Sorry.
