### ISSUE TITLE
Nav tab behavior for zero data? 

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#225]
What should the nav tabs display if a user has no checkouts, no requests, and no fines? 

## Requests
![zero requests](https://user-images.githubusercontent.com/5402927/61753819-9420f200-ad65-11e9-868c-943cd668d20a.png)

## Fines
![0-fees](https://user-images.githubusercontent.com/5402927/61753834-9e42f080-ad65-11e9-85c0-da622393a712.png)

**Comment by camillevilla** [comment]
Ran into some testing issues, but my proposal would be something like this: 
Throw an empty space in the span to keep the highlight size sort of even?? 

![Screen Shot 2019-07-23 at 4 34 51 PM](https://user-images.githubusercontent.com/5402927/61755090-e6b0dd00-ad6a-11e9-8fa1-05c341965932.png)

**Comment by jvine** [comment]
Discussed this with @cbeer earlier and decided there would be an explicit "0" status for each.

First show red conditions (blocked, recalls, payable fines) or green (pickups), then yellow (overdues, fines accruing), then just data (OK, 3, 0, $0.00).
