### ISSUE TITLE
Add check for number of unseen renewals remaining = 0

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#237]
@mejackreed ran into this issue when trying to renew an item in demo. 
Once a user has 0 `unseen renewals remaining`, they cannot renew the item and must bring it to the desk. Let's add a more specific error message than "Sorry! Something went and {title} was not renewed."

<img width="1131" alt="Screen Shot 2019-07-24 at 11 59 16 AM" src="https://user-images.githubusercontent.com/5402927/61820739-7f4a6a00-ae0a-11e9-97f7-47ad7f9b5132.png">

- [x] confirm whether we check unseen renewals remaining. 
- [x] If not, add a method that we can use for picking an error message

Current My Account error message is: "Only {x number of renewals} allowed for this item"

**Comment by jgreben** [comment]
The reason for the failed renewal may already be included in the web services response.

**Comment by cbeer** [comment]
Should we also hide the renewal button entirely? Or add a note to the record?

**Comment by camillevilla** [comment]
It seems like we'll still need some kind of error or note for the case where someone tries to "Renew all" and some of their overdue books are no eligible. Defer to @jvine on the desired UI here, but this doesn't block someone from confirming the logic now.

**Comment by cbeer** [comment]
I think `Renewal all` only renews eligible material?

**Comment by camillevilla** [comment]
@mejackreed noted that a new policy re: renewals was launched last week.
We'll check in with @saseestone and have a story time on this later this week.

**Comment by shelleydoljack** [comment]
I was hoping that the `circulation/itemCircInfo/advise` action might help us figure out whether the item can be renewed with data in the field `secondaryAdvice` but I tried getting advice for an item that we say is renewable for SUPER1, barcode 36105228833088 but this is the response:
```
{
    "primaryAdvice": "CHECK_IN",
    "item": {
        "resource": "/catalog/item",
        "key": "12735651:1:1"
    },
    "currentStatus": "CHECKED_OUT",
    "dueDate": "2019-08-05T23:59:00-07:00",
    "secondaryAdvice": [
    ]
}
```
I tried renewing the item that caused the issue during the demo and the API returns a response with a prompt:
```
{
    "messageList": [
        {
            "code": "hatErrorResponse.7703",
            "message": "Override required to exceed unseen renewal limit."
        }
    ],
    "describeUri": "/exception/simplePrompt",
    "promptRequired": true,
    "dataMap": {
        "promptType": "CIRC_UNSEEN_RENEW_LIMIT_OVRCD",
        "promptRequiresData": true,
        "promptDataType": "string"
    }
}
```
We can provide an override to allow the renewal but I think this needs to be discussed with Sarah.

**Comment by jvine** [comment]
The bulk renewal button is meant to indicate the number of items that are actually eligible for renewal, matching the number of items that show the little "renewable" icon in the list. 

Clicking "Renew 3 eligible items" should renew those 3 (or however many) items, confirm that 3 items have been renewed, and remove the "renewable" icons. There should be no failure from attempting to renew ineligible items. 

Items that are not renewable should have an individual status that indicates why they can't be renewed (too soon, no unseen renewals left, reserve item, etc.).
