### ISSUE TITLE
Patron info labels on the summary page shouldn't wrap to new lines

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#255]
![Screen Shot 2019-07-25 at 14 36 24](https://user-images.githubusercontent.com/111218/61910460-9d3acc00-aee9-11e9-8f9c-a9d194808199.png)

**Comment by jvine** [comment]
Okay, this works:
    `<dt class="col-5 col-sm-4 col-md-3 col-lg-2 `
    `<dd class="col-7 col-sm-8 col-md-9 col-lg-10 `

(... on everything but iPhone 5/SE. This is a *very* small category.)

XS
<img width="409" alt="Screen Shot 2019-07-26 at 2 54 07 PM" src="https://user-images.githubusercontent.com/6945691/61983665-20c1ef00-afb6-11e9-87d1-63ac19d44c2e.png">

SM
<img width="433" alt="Screen Shot 2019-07-26 at 2 54 26 PM" src="https://user-images.githubusercontent.com/6945691/61983708-51098d80-afb6-11e9-9d1a-2b7cb6a4ea54.png">

MD
<img width="539" alt="Screen Shot 2019-07-26 at 2 55 03 PM" src="https://user-images.githubusercontent.com/6945691/61983735-67afe480-afb6-11e9-9c3c-d2c0293cbae3.png">

LG
<img width="550" alt="Screen Shot 2019-07-26 at 2 55 17 PM" src="https://user-images.githubusercontent.com/6945691/61983742-6da5c580-afb6-11e9-9838-a19633ef51d2.png">
