### ISSUE TITLE
Figure out how many faculty members check out material to their research groups

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#262]

**Comment by saseestone** [comment]
We got this data, but it's for active current checkout only.  (Not historical transactions that have happened in the past year.)

Data is: On Bodoni, there are currently 94,341 charge records of which 2,709 of them are for groups. Of these, 97 unique users created the charges. Of these 97 users, 32 are proxies and 65 are sponsors.

Translation: small but not none.  

Got approval to move forward with removing the question for the faculty sponsor if we can't display the faculty member's "group" checkout to the proxies without introducing issues into the app.  

@shelleydoljack can we put in a request to SD have this data added to the API in the future?

**Comment by cbeer** [comment]
👍
