### ISSUE TITLE
Display the actual research group status to the faculty sponsor

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#268]
Sponsors and their research groups may have different patron status (ok/blocked/etc), so showing the faculty's status for the group is misleading

We should be able to use the status of any of the proxy members as the group status instead (because proxy statuses are magically linked in Symphony)... HOWEVER:

- why aren't the faculty2 proxies getting the same status (some say OK, some say Blocked).

**Comment by saseestone** [comment]
Our (Sarah/Shelley) understanding of the proxy user status has changed. We now know that we need to be displaying the "official" group user status (defined in Symphony) as the "status" in the "Proxies" tab.  Additionally for all proxy accounts, we need to display the **group user status** on the "Proxy last name" tab, and NOT the user status that appears in the user account.  

Shelley opened #278 to track work on displaying the user group status.

**Comment by cbeer** [comment]
👍 Sounds like this ticket is now obsolete then.

**Comment by saseestone** [comment]
ugh...don't drop your coffee cup on your keyboard and reopen issues.....
