### ISSUE TITLE
What is the app behavior when a patron is blocked?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#295]

**Comment by jvine** [comment]
Blocked patrons can see everything.

They cannot renew checkouts.
- suppress the bulk Renew button on Summary and Checkouts
- will the item-level renewal button be suppressed automatically by the eligibility check?

They cannot modify requests. 
- suppress the item-level "Change or cancel" buttons.

They can pay fines.

**Comment by jvine** [comment]
Suppress bulk renewals by disabling the blue button:
- change its background color to **$cool-grey 80%** `rgba(77,79,83,0.8)` 
- change its text to "Renewals blocked"

<img width="226" alt="Screen Shot 2019-07-30 at 1 13 07 PM" src="https://user-images.githubusercontent.com/6945691/62161885-f92b9900-b2cb-11e9-885a-061c333c1e8c.png">
<img width="267" alt="Screen Shot 2019-07-30 at 1 13 01 PM" src="https://user-images.githubusercontent.com/6945691/62161886-f9c42f80-b2cb-11e9-913d-f2463a2da7e9.png">

Suppress item-level renewals by:
a) removing the item-level buttons, or
b) replacing the buttons with the reason specified in #349,
whichever is more efficient. (I slightly prefer the first if it doesn't add complication to #349.)

Suppress item-level request changes by removing the button.
