### ISSUE TITLE
Integration with ILLIAD

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#300]
Patrons currently use sulils.stanford.edu to view the status of their ILL requests, but Symphony and BorrowDirect requests show up on the Requests tab. This is confusing for our users because we route their hold/recall requests to one of those services automatically.

We want to show both ILL + Scan requests in MyLibrary. 

TODO:
- [ ] Get some fixture data for our test users (or actually ILL some stuff?)
- [ ] Determine how to use ILLIAD `TransactionStatus` field to filter the displayed results (from @saseestone)

Cory did some investigation in #787 and determined:

> It appears that user-initiated requests in Illiad are made via an account that matches that users SUNET ID. We can make a request to the Illiad API for requests from a particular user:
> https://{ILLIAD_API_URL}/ILLiadWebPlatform/Transaction/UserRequests/{SUNET_ID}

> How the request information displayed in MyLibrary could map to the Illiad API response:
> 
> - **Deliver to:** Stanford (hard coded) or `ItemInfo4` (has library code e.g. GREEN)
> - **Not needed after:** in transit (hard coded) (`NotWantedAfter` is also available, but hard-coded is parity)
> - **Title:** `LoanTitle`
> - **Author:** `LoanAuthor`
> - **Requested:** `CreationDate` or `TransactionDate`
> - **Source:** ILL (currently BorrowDirect (hard coded) or `SystemID` (has values like `Reshare:stanford`))
> - **Call Number:** `CallNumber` (mostly this is unpopulated for Borrow Direct requests that I found)

If we can show users all the relevant ILL information, we can also remove (or adjust) the links directing uses to sulils: https://github.com/sul-dlss/mylibrary/blob/main/app/views/requests/index.html.erb#L76-L85

---

Here's what ILLIAD shows for a scan:

![Image](https://user-images.githubusercontent.com/111218/234956385-5eb48eba-9cd3-4dd6-903c-a964785ca9b4.png)
![Image](https://user-images.githubusercontent.com/111218/234956386-8deb69fc-893e-4211-923d-abc8671f919b.png)

**Comment by saseestone** [comment]
@hudajkhan I finally got a chance to write up some documentation for ILLiad & MyAccount, and I hope it proves useful...

https://docs.google.com/document/d/143O12M4HpvJPVbxdKE094KyNNwa3SE16JrBRm1nbRlw/edit.
