### ISSUE TITLE
Add more static text to requests footer to link out to e.g. link out to scan requests in ILLIAD

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#309]

**Comment by jvine** [comment]
- `Requests requiring approval are not listed here until they have been approved &mdash; typically 1-3 days before your scheduled visit.`
- `Scan requests are listed in <link>.`
- `Requests made through Stanford Libraries Interlibrary Services are listed in <link>.`

<img width="703" alt="Screen Shot 2019-07-29 at 12 09 52 PM" src="https://user-images.githubusercontent.com/6945691/62075392-cd3fe300-b1f9-11e9-9ef0-aafa1ffa157c.png">

**Comment by cbeer** [comment]
Do we also want to link to the requests app for unapproved mediated requests?

**Comment by jvine** [comment]
I think only approvers can see anything in the requests app? Patrons only have the link in the confirmation email they were sent.
