### ISSUE TITLE
Flash messages for bulk renewals

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#325]
A misunderstanding on the flash message situation for bulk renewals:  since it's possible for one or more renewals to fail (though presumably not for eligibility reasons), a single summary flash message wasn't feasible. I expected splitting the messages to give a max of 2: 
- "Success! 23 items were renewed"
- "Sorry! 4 items were not renewed"

In fact, each item now gives an individual flash message. This is fine for small 2-3 items, but is overwhelming when there are more than a few; and will quickly obscure the full page. 

At the same time, there's value in the specific information about which items were affected. 

Wondering if we can instead:
- give a single flash message for the successful renewals, and a single message for failures
- list the affected titles in the single message

This would still be a large message for a mass renewal, but it's _less_ large, and a single dismiss action; and the list is more easily scannable than the separate messages.

**Before** (pretending there's a failure which I haven't actually seen)

<img width="945" alt="Screen Shot 2019-07-29 at 1 59 19 PM" src="https://user-images.githubusercontent.com/6945691/62084734-ce2f3f80-b20e-11e9-911a-e6098cf90b1f.png">

**After**

<img width="950" alt="Screen Shot 2019-07-29 at 2 07 15 PM" src="https://user-images.githubusercontent.com/6945691/62084407-23b71c80-b20e-11e9-8622-3ba9c6c86f26.png">

(Not certain about the text of the failure message - I want something generic. Suggestions?)

**Comment by jkeck** [comment]
Should the `contact us` link to the modal pop-up thing for the Access Services contact form or something else?

(alternatively, is just stating to Contact Us enough for right now enough, this may get tricky being in an i18n file.

**Comment by jvine** [comment]
Unlinking the text is fine; there's a link right above.
