### ISSUE TITLE
Payment Type translations for Payment History

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#347]
When displaying the Payment History, please use the following translations for "Payment Type"

Payment type => "(translation)"
Autorefund => "Returned"
Cancel => "Removed"
Cardswipe => "Paid by credit card"
Cash => "Paid by cash"
Check => "Paid by check"
Clms-Rtnd => "Processing claim"
Creditacct => "Returned"
Creditcard => "Paid by credit card"
Forgiven => "Forgiven"
Lib-Error => "Removed"
None => "Returned"
Refund => "Removed"
Returned => "Returned"
Trans-bill => "Forgiven"
U-replaced => "Replacement provided"
Xrembill => "Removed"

**Comment by shelleydoljack** [comment]
Fixed by #341
