### ISSUE TITLE
Update text on the  "contact library" form

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#359]
The modal title should reflect the library being contacted.

The `To` name + address should be the one we're contacting.

Also, the confirmation flash message should be updated too.

**Comment by jvine** [comment]
Here's the relevant mockup
<img width="372" alt="Screen Shot 2019-07-30 at 4 56 28 PM" src="https://user-images.githubusercontent.com/6945691/62173480-115ee080-b2eb-11e9-99e3-2a2980bed87c.png">

Modal title retains the name of the link that opened it
To name & address reflect the library being contacted.
