### ISSUE TITLE
Custom disabled button styling

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#360]
Disabled blue button:
- change its background color to **$cool-grey 80%** `rgba(77,79,83,0.8)` 

<img width="226" alt="Screen Shot 2019-07-30 at 1 13 07 PM" src="https://user-images.githubusercontent.com/6945691/62161885-f92b9900-b2cb-11e9-885a-061c333c1e8c.png">
<img width="267" alt="Screen Shot 2019-07-30 at 1 13 01 PM" src="https://user-images.githubusercontent.com/6945691/62161886-f9c42f80-b2cb-11e9-913d-f2463a2da7e9.png">

**Comment by jvine** [comment]
(Confirmed that all our button types in their default disabled state fail WCAG level AA contrast tests. Not all auditors catch this, so the same issue probably exists in our other apps.)
