### ISSUE TITLE
Change wording of "Contact Access Services" link & dialog title

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#363]
Based on feedback from Circ staff:

In the banner
- change `Contact Access Services` link text to `Circulation & Privileges`
- add `role="img"` to the email and phone svg elements
- add a title to each svg:
   - `<title>Email</title>`
   - `<title>Phone</title>`

In the dialog
- change the title of the popup to 'Contact Circulation & Privileges`
- add nowrap/overflow to truncate the `<h2>` at one line (otherwise it wraps on mobile and can push the Send button offscreen)
- change the "To" address to `Circulation & Privileges (greencirc@stanford.edu)`

<img width="704" alt="circ   privs" src="https://user-images.githubusercontent.com/6945691/62172572-87f9df00-b2e7-11e9-99f9-64139a8fb1a1.png">

<img width="373" alt="Screen Shot 2019-07-30 at 3 50 22 PM" src="https://user-images.githubusercontent.com/6945691/62172480-36515480-b2e7-11e9-88d4-b70ac6fc1fb1.png">

**Comment by jkeck** [comment]
Picking this up along w/ #359 as they'll touch the same code-paths.
