### ISSUE TITLE
Proxy accounts should see and pay only the fines associated with their account

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#388]
Due to privacy concerns, proxy users should only be able to view and pay the fines associated with their proxy account.  They should not be able to view or pay the fines associated with other proxy accounts. 

Sponsors should be able to view and pay fines for both their individual account and all the proxy accounts. (#402)

**Comment by jvine** [comment]
For proxy groups, retain the "Payable" header, but replace the remaining content of the page-section (button, sort, list of fines) with static text:

"The research group has unpaid fines that may affect the status of all proxies."

<img width="548" alt="Screen Shot 2019-08-01 at 9 59 40 AM" src="https://user-images.githubusercontent.com/6945691/62312513-349ca380-b443-11e9-8a63-823898201e67.png">
