### ISSUE TITLE
Analysis of work needed to add integration with payments

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#39]
Expected outcome:
- [x] confirming any configuration or authorization needed on the payment processors side
- [x]  a new ticket describing the payments workflow that we'll need to implement

**Comment by jgreben** [comment]
Configuration needed: shared_config items: 
- Cybersource profile `name`
- Cybersource profile `access_key`
- Cybersource profile `secret_key`

See https://github.com/sul-dlss/mylibrary/issues/40 for implementing the payments workflow
