### ISSUE TITLE
Payment processing UX issues, part 1: individuals

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#399]
For an individual user, the state of the UI on returning from a successful fine payment is really confusing.

The return page shows:
- nav status:  "**payment processing**" (...okay, but see comments)
- flash "Success! $41.00 paid..." (correct)
- Payable: **$41.00**  (???  contradicts nav status)
- no payment button (correct, but confusing with Payable amount shown above)
- fines are listed in payment history because the response was quick; I know this won't always be the case.

<img width="400" alt="Screen Shot 2019-08-01 at 1 57 10 PM" src="https://user-images.githubusercontent.com/6945691/62328203-53149600-b467-11e9-8672-84a1ac22c2cb.png">

When I refresh the page, it shows:
- nav status:  "**payment processing**"  (now it's wrong)
- no flash  (correct)
- Payable: **$0.00**  (correct)
- no payment button (correct)
- fines are listed in payment history (correct)

<img width="400" alt="Screen Shot 2019-08-01 at 1 58 12 PM" src="https://user-images.githubusercontent.com/6945691/62328252-72abbe80-b467-11e9-91fa-39dda6cd0e36.png">

Both of these states are inaccurate and confusing.

1. The "payment processing" text in nav status is too long and breaks on mobile [Edit: I thought "processing" would work, but it's still too long. "pending" fits.]
  
2. The nav status and Payable headers should always match - both should be "pending" when the payment has not been processed, and both should be "$0.00" when it has. 

3. If there is no content in the Payable fines list - i.e. the fines are already showing in Payment history - can the nav status and Payable header both show $0.00 right away? And show "pending" only when the fines are actually still listed?

**Comment by mejackreed** [comment]
One edge case.. if an item is overdue and assumed lost, you get a lost bill. 

You either have to return the item, and you have to pay overdue fine
You pay the lost item and now you owe $$ for overdue
