### ISSUE TITLE
Use ruby_sop Card Payments Implementation

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/mylibrary#40]
**Option 1) Integrate CyberSource `ruby_sop` into project**
`ruby_sop` is a Sinatra app that includes Class, View, and Controller with supporting JS for generating the secure payment forms.

See example: https://github.com/sul-dlss/mylibrary/tree/payment-implementation-example/vendor/ruby_sop

- Decide where to place ruby and ruby templating files in MyLibrary project and create appropriate routes, i.e. integrate fully within `app` or put in `vendor`?
- Use Settings to retrieve `access_key`, `secret_key`, and `profile_id`
- Customize "signed data fields" in `signeddatafields.erb`:
 -- `transaction_type` = `sale`
 -- `amount`
 -- `currency` = `USD`
 -- `reference_number` = `{symphony billKey}-{symphony billSequenceNumber}`
 -- `merchant_defined_data1` = `{symphony userID}_{symphony group payment flag}`
- Specify 👆 list of `signed_field_names` in `signeddatafields.erb`
- Specify `unsigned_field_names` = `merchant_defined_data1` in `signeddatafields.erb`
- POST parameters to `store_front`:
 -- group payment flag
 -- bill amount
 -- bill key
 -- bill sequence
- Customize `receipt` 
 -- translate request param key into display value (see mapping below)
 -- capture params:
 --- `decision`
 --- `req_bill_to_email`
 -- display appropriate conditional messages if payment `decision` was accepted or not, and email a copy of the receipt to them or a message about a declined payment.
- Customize views per design specs

**Option 2) Use the existing Symphony web payment PHP forms** 
Sending a POST request to `{Symphony}/secureacceptance/payment_form.php?` and use the following post params and change the link in the existing `receipt` to the new MyLibrary App. 

name='amount'
value=[:billamount] // total amount of bill (sum of all indiviual bills)
        
name='billseq'
value=[:billno] // `billSequence number` || `{lowest billSequence number}-{highest billSquence number}`
        
name='user'
value=[:userID]
                
name='session_id'
value=[:session]
        
name='group'
value=[:group] // `G` || nil

**Comment by jgreben** [comment]
`receipt` display values for request params: 

'Order Number:' => 'req_reference_number',
 'Library ID:' => 'req_merchant_defined_data1',
 'Amount:' => 'req_amount',
 'Date and Time:' => 'auth_time',
 'Result:' => 'message',
 'Transaction ID:' => 'req_transaction_uuid',
 'Last Name:' => 'req_bill_to_surname',
 'First Name:' => 'req_bill_to_forename'

**Comment by jgreben** [comment]
Download `ruby_sop`: http://apps.cybersource.com/library/documentation/dev_guides/Secure_Acceptance_Checkout_API/html/wwhelp/wwhimpl/js/html/wwhelp.htm#href=creating_profile.05.8.html

**Comment by cbeer** [comment]
Thanks @jgreben. 

I've checked in with @camillevilla; for now, let's pursue option 2. There's significant complexity introduced by option 1, and we can revisit it after reaching parity with the current application.

**Comment by jgreben** [comment]
On existing PHP pages, I just notices that the "View online payment refund policy" link is broken. Need to fix that...

**Comment by thatbudakguy** [comment]
was resolved by #901
