### ISSUE TITLE
Accessibility considerations for nav tabs

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/mylibrary#41]
stub for @jvine, follow on from #15 / #35

**Comment by jvine** [comment]
Trying to figure out how to make the current selection perceivable by a screen reader. Currently all 4 links read the same way. `aria-current="page"` is supposed to work, but doesn't on any browser/SR combination I've tried so far. 

Alternate:
- current link gets `aria-describedby="current"
- add `<span class="sr-only" id="current">current page</span> somewhere

Just making notes for the moment and recording the issue, no action required yet.

**Comment by jvine** [comment]
Superseded by #306. Closing.
