### ISSUE TITLE
In Requests, we should use the owning library as the "Source" library

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#453]
Looks like in the Requests tab, we're using the placedLibrary to determine "Source".  The problem is most requests placed in SearchWorks have a placedLibrary = SUL.  (As opposed to the fixture users that I created, which all inherited my placedLIbrary = GREEN)

Instead, we should be using the owning library for "Source".  Possible?

In the example from the snapshot 👇 the first item has owning library = GREEN.  Second item has owning library = SAL3. 

![image](https://user-images.githubusercontent.com/14897546/62595152-0cbd9d80-b892-11e9-9abf-8331738a9bb0.png)

**Comment by cbeer** [comment]
Is the owning library the same library we show as the checked out source (from `item > library`)? And, what about requests for things that don't have associated items yet?

**Comment by saseestone** [comment]
Yes, it should be the same as for checked out source.

For requests with no items associated, there should still be a library associated with the title record. But I'll admit that I don't know where that data would live in the web services calls, and if you have access to it. I can set up a test user using searchworks-dev on a request with no item info.
