### ISSUE TITLE
Missing Borrower on Fines / Proxies tab

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#457]
Just noticed this on dev - I can't see it on prod, so I'm not sure if it's a real issue.

On the Fines / Proxies tab, the item detail shows a label for Borrower, but no borrower name. Is this a) an anomaly with test data, b) a side effect of proxy fines privacy decisions, or c) something else?

If a value can't be displayed, its label shouldn't be either.

<img width="753" alt="Screen Shot 2019-08-09 at 11 54 03 AM" src="https://user-images.githubusercontent.com/6945691/62802297-67c2e080-ba9c-11e9-8b31-4770a2d9ac3d.png">

**Comment by jvine** [comment]
Oh. Proxy borrowers also missing on the Checkouts page, in dev. Hopefully just a dev issue?

**Comment by cbeer** [comment]
This is with your test account? I'd guess your proxies don't follow the naming convention for normal proxy accounts.
