### ISSUE TITLE
Renew all (eligible) checkouts

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#49]
Q: Can this be done in a single API request, or do we need to iterate through the checkouts and fire off a separate request for each?

Button:
<img width="237" alt="Screen Shot 2019-07-10 at 07 53 58" src="https://user-images.githubusercontent.com/111218/60979618-e2ef7600-a2e7-11e9-945f-889f0111f364.png">

Flash message:
<img width="386" alt="Screen Shot 2019-07-10 at 07 50 14" src="https://user-images.githubusercontent.com/111218/60979546-c2272080-a2e7-11e9-9ed2-46497b06eaf6.png">

**Comment by mejackreed** [comment]
The documentation indicates that we will need to send individual requests. However we should check this first by sending an array of items in our renewal request:

https://github.com/sul-dlss/mylibrary/blob/master/app/services/symphony_client.rb#L82-L86
