### ISSUE TITLE
Failure message possible for users with no library account at login

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#490]
We've had 3 feedback messages from users that are trying to log into My Library Account and they don't have a Symphony user account.  Can we work on failure message for this particular failure?

Is it a specific failure?

**Comment by jvine** [comment]
Related: https://github.com/sul-dlss/mylibrary/issues/336#issuecomment-525491781

**Comment by jvine** [comment]
Users are trying to log into My Account when they are not eligible for an account and are only trying to access online resources. Two changes to address this: 

1. change initial messaging on the page
2. make the error message more informative

### Change page text

- [ ] Change `h1` text to `Log in to see your checkouts, requests, fines & fees`
- [ ] Add 30px margin below the `h1`
- [ ] Remove the current `<p>` text from below the `h1`
- [ ] Add a `<div class="page-section">` at the bottom with this content:

   ```
   <h2>Looking for online resources?</h2>
   <p>A library account is not required to access Stanford's e-resources. <br> Find e-resources in <a ...><svg...>SearchWorks</a> and log in there with your SUNet ID.</p>
   ```

<img width="1162" alt="my library login" src="https://user-images.githubusercontent.com/6945691/67428780-b1976f00-f593-11e9-94c7-7853febfbbf7.png">

### Change error message

<img width="1128" alt="my library error" src="https://user-images.githubusercontent.com/6945691/67429108-5154fd00-f594-11e9-8f4e-10bdf56354a5.png">

```
<p class="h3">Unable to log in. Your SUNet ID is not linked to a library account.</p>
<ul><li>You do not need a library account to access Stanford's e-resources.</li>
<li>A library account is created for patrons who are eligible to check out library materials.</li>
<li>If you believe you should have an account, contact <a href="mailto...">Circulation & Privileges</a> for assistance.</li></ul>
