### ISSUE TITLE
In Fines detail, can item info be added to contact library email

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#491]
Library circulation staff have received a few "contact library" emails from the app - and specifically from the item detail in the Fines tab:

![image](https://user-images.githubusercontent.com/14897546/66518493-3d8c9f80-ea9a-11e9-9cde-abe6594ca8bf.png)

The lightbox that displays doesn't show the user much about what information is going to be brought over into the email, but it's clear that they assume that we'll get information about the item.  So we get responses like this:

-----Original Message-----
From: contact@mylibrary.stanford.edu <contact@mylibrary.stanford.edu>
Sent: Wednesday, October 2, 2019 11:48 AM
To: sciencelibrary <sciencelibrary@stanford.edu>
Subject: Circulation & Privileges Question/Comment from My Library App

Name: Abhimanyu Banerjee
Email: manyu@stanford.edu
Comment: Hi the book is not lost. Can I return sometime

Message sent from: 'My Library Account'
Host: mylibrary.stanford.edu
IP: 10.39.101.205

Circulation staff are wondering if item information can be added to the email, so that we know which item they are referring to.

**Comment by dnoneill** [comment]
@saseestone do they want information besides the barcode?
