### ISSUE TITLE
When patron information is empty, show a helpful error page

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/mylibrary#501]
Sometimes for various reasons SymWS returns nil for a patron info request. This can happen, for example, when the person has an item in their request or checkouts list that is locked during a Symphony reindexing update during the evening. Here is a message that was captured using verbose logging at the same time a Honeybadger error was reported

`undefined method `dig' for nil:NilClass` (for `fields.dig`)
corresponds to:
```
{"messageList":[{"code":"hatErrorResponse.225","message":"The bibliographic record is locked for text update"}]}
```
We need to redirect to a helpful page explaining what might be going on in for various error codes.

**Comment by jkeck** [comment]
Might be somewhat related to #495

**Comment by thatbudakguy** [comment]
closing since we're no longer using symphony.
