### ISSUE TITLE
Summary page and nav bar with dynamic content

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#52]
The summary page and the nav page display suspiciously similar status data for each of the tabs: 

<img width="380" alt="Screen Shot 2019-07-10 at 08 03 17" src="https://user-images.githubusercontent.com/111218/60980358-2f878100-a2e9-11e9-8943-3885474c6835.png">

<img width="382" alt="Screen Shot 2019-07-10 at 08 02 59" src="https://user-images.githubusercontent.com/111218/60980340-25fe1900-a2e9-11e9-8963-2091d0ca7b66.png">

Hopefully all the necessary information can be retrieved in a single request.

**Comment by camillevilla** [comment]
Closed by #207
