### ISSUE TITLE
Add line to COVID-19 alert banner 

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#530]
We need to **add** a line to the existing COVID-19 alert banner letting users know that if they have returned materials to a bookdrop or via the mail, staff cannot process them.  And therefore they will still be listed in Checkouts.

Perhaps:
"Library materials returned to a library bookdrop or by mail are being held for processing, and will remain in the Checkouts list until libraries reopen."  

@jvine would love your eyes on the text before it deploys...

**Comment by jvine** [comment]
```
<br><br><b>Returned materials</b> <br>
Library materials returned to a library book drop or by mail are being held for processing. <br>They will remain in your Checkouts list until libraries reopen.
```

<img width="637" alt="Screen Shot 2020-04-06 at 3 09 51 PM" src="https://user-images.githubusercontent.com/6945691/78610109-057fd280-7819-11ea-97f9-94b156ae3741.png">
