### ISSUE TITLE
Bulk changing/canceling requests

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#54]
<img width="361" alt="change all requests" src="https://user-images.githubusercontent.com/6945691/61568430-1ba1f480-aa38-11e9-8102-ee856ee301db.png">
(Updated screenshot 7/19 - JV)

**Comment by jkeck** [comment]
One thing that we'll have to keep in mind here (and potentially in #51) is that certain items should only be deliverable to certain libraries based on home library or location.

See https://github.com/sul-dlss/sul-requests/blob/37986c1ea750aae8b3ac7b4e109c5d20d67c4964/config/application.rb#L87-L93 and https://github.com/sul-dlss/sul-requests/blob/37986c1ea750aae8b3ac7b4e109c5d20d67c4964/config/application.rb#L107-L133

**Comment by mejackreed** [comment]
@jkeck is there a way we want to share that logic between the two applications, or should we just copy and remember ?

**Comment by jkeck** [comment]
We don't currently have a good way of sharing this data between applications.

**Comment by mejackreed** [comment]
@jvine are there certain affordances we should make for @jkeck comment here about the libraries that are available to be picked up at?

**Comment by jvine** [comment]
Okay. This just got complicated. I think we may not be able to do a bulk change of pickup library.

Some items have a location of PAGE-XX, which means "can only be paged to XX Library". If the user has a combination of items that can be paged to any library, and items that are PAGE-XX, any bulk change _cannot_ change the PAGE-XX items. 

I think we can only control for this at the individual item level. So maybe the bulk options are only "change date or cancel everything" (i.e. I'm going on a research trip to Tanzania), and the library can only be changed at the item level. 

(Note that the change pickup library feature is also beyond parity, but a common request.)

**Comment by saseestone** [comment]
Agreed that we can't bulk change because of the logic needed to present the option accurately.

**Comment by cbeer** [comment]
Notes
- Changing location in bulk is difficult (because items may have restrictions about where they can be  sent).
- Can't cancel BorrowDirect requests (because the hold isn't created in the ILS until the item arrives)

There's too many variables, so we're deferring this whole feature (and it shouldn't be too onerous for our users).
