### ISSUE TITLE
Button for Scheduling Green paging pickup appointments

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/mylibrary#541]
Given a Patron:

* has paged materials available for pickup at Green
* is an eligible patron
   * for launch: faculty, students, staff, academic staff, postdocs, fellows, and visiting scholars with a current Stanford ID card, plus proxy borrowers
      * @saseestone to add Symphony user profiles info here
   * may expand later to include SUL cardholders (Continuing Studies instructors, fee borrowers)

The Patron should:

* See a button on the Summary and Requests index views to schedule a pickup at Green Library
* Click the button and have the form autopopulate visible, editable fields with their name (`name`) and email (`email`), and hidden fields with their name (`sul_myaccount_name`), email (`sul_myaccount_email`), and SUNetID (`sul_myaccount_sunetid`)
* Submit the form to schedule a time and receive an email

**Mockups**
* [Static mockups](https://docs.google.com/document/d/13enMGvD-vT73r44NOQyOgYSqustAmXzNgDpfYEmgyNU/edit)
* [JSFiddle demo](https://jsfiddle.net/anarchivist/bp6fzxnh/)
* [Dynamic mockups](https://anarchivist.github.io/myaccount-so/index.html)

**Oncehub Form ID**
StanfordLibrariesPagingPickupGreenLibrary

**Comment by saseestone** [comment]
User groups and Symphony user profiles:

faculty = CNF, MXF
students = MXD, RED, REG, REG-SUM, REU, REU-SUM
staff = CNAC, CNS, MXAC, MXS

**Comment by saseestone** [comment]
Also add MXAS to the staff group (Visiting Scholars).  Complete list is:

faculty = CNF, MXF
students and postdocs = MXD, RED, REG, REG-SUM, REU, REU-SUM
staff = CNAC, CNS, MXAC, MXAS, MXS
