### ISSUE TITLE
Button for scheduling SPEC visits

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/mylibrary#542]
Given a Patron:

* has paged materials available for use in SPEC
* is an eligible patron
   * for launch: faculty, graduate students, and postdocs
   * may expand later to include others

The Patron should:

* See a button on the Summary and Requests index views to schedule a visit at Special Collections
* Click the button and have the form autopopulate visible, editable fields with their name (`name`) and email (`email`), and hidden fields with their name (`sul_myaccount_name`), email (`sul_myaccount_email`), and SUNetID (`sul_myaccount_sunetid`)
* Submit the form to schedule a time and receive an email

**Mockups**
* [Static mockups](https://docs.google.com/document/d/13enMGvD-vT73r44NOQyOgYSqustAmXzNgDpfYEmgyNU/edit)
* [JSFiddle demo](https://jsfiddle.net/anarchivist/bp6fzxnh/)
* [Dynamic mockups](https://anarchivist.github.io/myaccount-so/index.html)

**Oncehub FormID**
StanfordLibrariesVisitSpecialCollections

**Comment by saseestone** [comment]
User groups and Symphony user profiles:

faculty = CNF, MXF
grad students = MXD, RED, REG, REG-SUM, REU
postdocs=

**Comment by saseestone** [comment]
Requirements changed on 5/28/20 to include "fellows and visiting scholars".

Visiting Scholars = MXAS
Fellows = CNAC

Confirmed on 6/1/20 via email
