### ISSUE TITLE
Text change + link around Building access

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#548]
Change label to "Library access"

Change "No access" text to "Not eligible during current phase of Research Restart Plan"

Add a link for all users below the button or "not eligible" text

`<a href="https://library.stanford.edu/returntoresearch">Current status of library services</a>`

<img width="548" alt="Screen Shot 2020-06-03 at 3 36 40 PM" src="https://user-images.githubusercontent.com/6945691/83695948-0c745880-a5b0-11ea-9e55-6e0a66f59988.png">

**Comment by cbeer** [comment]
Fixed in the branch.
