### ISSUE TITLE
Add pickup scheduling capability for BUSINESS

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/mylibrary#567]
BUSINESS manages their appointments through LibCal.  We can look into doing a similar iframe embed that we do for ScheduleOnce (but will need to build the hooks in to have different scheduling embeds).

If that doesn't work, we can link to their libcal instance instead.

@jkeck / @anarchivist have the details about their libcal instance and how to embed it (they have a script that injects an iframe and we may want to do the same thing we did w/ ScheduleOnce and just modal the iframe that would have been generated).

**Comment by anarchivist** [comment]
After poking at this it seems like we should be able to get a generated iframe as we did with ScheduleOnce. The JS injects the following iframe:

```
<iframe id="mysched_69353-iframe" src="https://api3.libcal.com/widget/appointments?u=69353&amp;lid=4596&amp;gid=9430&amp;iid=5088&amp;t=At%20the&amp;ncache=1594315688622" height="463" width="560" style="padding:0; margin:0; border:0; overflow-x: hidden; overflow-y: scroll;" title="At the"></iframe>
```
