### ISSUE TITLE
Add regular non-academic staff, temp/casual staff, and emeritus staff to eligible group for SPEC visits and GREEN and EAL entry 

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/mylibrary#590]
Non-academic (regular) staff and temp-casual staff should now be able to schedule visits to Special Collections, and entry appointments for Green and EAL. 

Regular staff: 
* Authentication privgroup: `stanford:staff` or `stanford:staff:otherteaching`
* SYM user profile: `CNS`, `MXS`, `CNAC`

Temporary staff:
* Authentication privgroup: `stanford:staff:temporary`
* SYM user profile: `MXS`

Casual staff:
* Authentication privgroup: `stanford:staff:casual`
* SYM user profile: `MXS`

**Comment by saseestone** [comment]
Above is all correct, but also add:

Emeritus staff:

- Authentication privgroup: stanford:staff:emeritus
- SYM user profile: CNAC

**Comment by jkeck** [comment]
For changes in requests eligibility overlays / ineligible error pages:
* Remove (including emeriti) from all the places it currently exists.
* Remove “academic” from “staff” where it exists.
