### ISSUE TITLE
Add affordance to check waitlist position for CDL items

### ISSUE THREAD

**Issue by jvine** [sul-dlss/mylibrary#597]
For Digital lending items, replace the waitlist position text with a button link that checks the position for that specific item.

Link follows the pattern for My Library with an icon in front - mockup shows Material Icons "sync"; not sure what's available to us:
<img width="642" alt="Screen Shot 2020-09-24 at 3 43 03 PM" src="https://user-images.githubusercontent.com/6945691/94208093-e2f07d00-fe7d-11ea-93b5-b40f46765f6d.png">

User clicks the link and one of two things happens.

### 1. (Preferred) Show an inline progress indicator of some kind (e.g. the pattern used on the tabs) then show the value as text.

<img width="627" alt="Screen Shot 2020-09-24 at 3 42 34 PM" src="https://user-images.githubusercontent.com/6945691/94208357-7f1a8400-fe7e-11ea-9b5d-fe8d16b3eeb6.png">

If the check fails, add an inline error message

<img width="700" alt="Screen Shot 2020-09-24 at 4 01 50 PM" src="https://user-images.githubusercontent.com/6945691/94208707-55159180-fe7f-11ea-8808-8e4a6228d0c6.png">

### 2. (Alternate) Open a popup that shows the waitlist position.
<img width="410" alt="Screen Shot 2020-09-24 at 3 55 53 PM" src="https://user-images.githubusercontent.com/6945691/94208384-90fc2700-fe7e-11ea-9762-a8ad4b772d11.png">

If the second approach is necessary for technical reasons, the width of the modal will need to be adjusted from its current massive size (which accommodates the calendar). Is it possible to maybe add:
```
width: fit-content;
min-width: 400px;
``` 
to the modal globally?

**Comment by jkeck** [comment]
Maybe this for the icon (which should be `CachedSharp`)?
```<svg viewBox="0 0 24 24">
  <path d="M19 8l-4 4h3c0 3.31-2.69 6-6 6-1.01 0-1.97-.25-2.8-.7l-1.46 1.46C8.97 19.54 10.43 20 12 20c4.42 0 8-3.58 8-8h3l-4-4zM6 12c0-3.31 2.69-6 6-6 1.01 0 1.97.25 2.8.7l1.46-1.46C15.03 4.46 13.57 4 12 4c-4.42 0-8 3.58-8 8H1l4 4 4-4H6z"></path>
</svg>
```

**Comment by jvine** [comment]
That's perfect.
