### ISSUE TITLE
Consider UI/UX for payments form + receipts

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#60]
- https://bodoni.stanford.edu/secureacceptance/payment_form.php
- https://bodoni.stanford.edu/secureacceptance/receipt.php

**Comment by jvine** [comment]
@jgreben it would also be helpful to know what the actual payment form looks like. do we know that yet?

**Comment by jgreben** [comment]
@jvine:

![Screen Shot 2019-07-15 at 1 34 57 PM](https://user-images.githubusercontent.com/3093850/61247505-124a1c80-a706-11e9-9280-e9b54d808486.png)

![Screen Shot 2019-07-15 at 1 35 22 PM](https://user-images.githubusercontent.com/3093850/61247509-14ac7680-a706-11e9-8e03-6c1677d30cc0.png)

**Comment by jvine** [comment]
After reviewing several other implementations of Cybersource on campus, I think we should do the following:

- add a popup (by preference) confirmation that we're sending you to a 3rd party processor
- style the form completely generically, only with a current SUL logo at the top

In this way a) we're being explicit, and b) we will be in line with other implementations that users may be familiar with, and less likely to raise any concerns. 

### Popup

<img width="377" alt="Screen Shot 2019-07-15 at 4 00 08 PM" src="https://user-images.githubusercontent.com/6945691/61254704-4b8c8780-a71a-11e9-80e4-833e8b32d063.png">

If a popup is not possible, then a single interstitial page will still be required, with the same confirmation message, something like this:

<img width="877" alt="Screen Shot 2019-07-15 at 4 33 07 PM" src="https://user-images.githubusercontent.com/6945691/61255661-4b8e8680-a71e-11e9-81f1-abb4f9e1da89.png">

### Form

<img width="1007" alt="Screen Shot 2019-07-15 at 4 36 16 PM" src="https://user-images.githubusercontent.com/6945691/61255733-b3dd6800-a71e-11e9-8167-445f4ef1e3e1.png">

### Logo (sized and with top padding added)

![StanfordLibraries-logo-cmyk-500](https://user-images.githubusercontent.com/6945691/61255248-914a4f80-a71c-11e9-86a9-3547b44fedc4.png)

**Comment by cbeer** [comment]
I assume the reskinning can happen at any time and doesn't need to be tied to the mylibrary launch?

**Comment by jvine** [comment]
Reskinning the third party pages can happen at any time.

Reducing / redesigning the interstitial pages should be tied to the launch, IMO. Fine payment is one of the pain points we want to improve with this work effort.

**Comment by jvine** [comment]
RDE example:  https://rdeapp.stanford.edu/MyMealPlan/StaffCardinal

**Comment by jgreben** [comment]
In DEV I already automated the interstitial pages which was easy to do.

Some background info on the difference between RDE's (and others') implementation vs ours: The  use the "oneclick" option which we cannot use because we need to interject some of our own custom variables in order to be able to automatically process the payments immediately on the back-end. Other merchants are able to reconcile their payments manually upon receipt of confirmation email or by other means, but we cannot do that due to the fact that AS staff are pretty much hands-off on bill payments and that the bills need to be cleared immediately upon payment.

**Comment by jgreben** [comment]
Here are screenshots of the current Test site. @jvine one more question: do we want to have CyberSource automatically email a receipt?

![Screen Shot 2019-07-17 at 9 36 56 AM](https://user-images.githubusercontent.com/3093850/61393825-a804b980-a876-11e9-858f-57a2cd3d8dda.png)
![Screen Shot 2019-07-17 at 9 37 07 AM](https://user-images.githubusercontent.com/3093850/61393826-a804b980-a876-11e9-814f-5034e6961cf9.png)

**Comment by jvine** [comment]
Cybersource looks good @jgreben. And yes, please - we should automatically email a receipt.

**Comment by jgreben** [comment]
@jvine I lied about not being able to customize the CyberSource receipt email.

We NEED to set: 
- [ ] Sender Email Address
- [ ] Sender Name

We CAN OPTIONALLY set:
- [ ] Send a copy to...
- [ ] Display a notification Logo
- [ ] Email Subject
- [ ] Email Header (text) 
- [ ] Email Footer (text)

Here is what a custom receipt looks like:
![Screen Shot 2019-07-17 at 10 55 37 AM](https://user-images.githubusercontent.com/3093850/61398813-abea0900-a881-11e9-8963-bfdbaf35186f.png)

**Comment by jvine** [comment]
Just notes so far...  @saseestone any input?

Sender email address:  [greencirc?]
Sender name:  **Stanford Libraries**

Send copy - no
Logo - same as the payment page
Email subject:  **Receipt from Stanford Libraries**
Header:  **It may take a few minutes for this payment to appear in My Library Account.**
Footer:  **If you have questions about your payment or account status, contact** [greencirc?]

**Comment by saseestone** [comment]
I think the sender email address and address for the Footer should be: sul-privileges@stanford.edu
✅on:
Sender name: Stanford Libraries
Send copy - no
Logo - same as the payment page
Email subject: Receipt from Stanford Libraries
Header: It may take a few minutes for this payment to appear in My Library Account.
Footer: If you have questions about your payment or account status, **contact sul-privileges@stanford.edu**
