### ISSUE TITLE
Remove some appointment links

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#619]
On Monday, Nov. 23, 2020 we need to remove some appointment links.  

Remove schedule access links for GREEN and EAST-ASIA
Remove schedule pickup links for GREEN, EAST-ASIA, BUSINESS and HOPKINS.

I'll be creating an issue in sul-requests for text changes to the Page form. I'll update this ticket when that one is created. (We're waiting for confirmation on the text.)

**Comment by mejackreed** [comment]
@saseestone Is there additional changes that need to be made here?

**Comment by saseestone** [comment]
nope.  Things are up to date for now.  Closing the issue.
