### ISSUE TITLE
Remove renewal eligibility for items with Item Cat5 of "NORENEW"

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#649]
We need to remove the hold override that we're currently passing when a user requests to renew an item that has a title-level hold. We also need to display to the user that they cannot renew the item.  If there is a hold, regardless of the hold level, we should display "No. Another user is waiting for this item."

Background:
The hold override is currently (i.e. in COVID times, when we aren't recalling materials from users) causing a bigger issue than it is meant to solve. It's allowing users to renew materials, even when there is a hold on the item for another user.  In non-COVID times, these title-level holds would convert to Copy level holds as soon as Symphony determined that the checked out copy was the only available copy. That determination happened daily via Symphony report.  In non-COVID times it made sense to error on the side of allowing the renewal for any hold that remained title-level.

But in COVID times, these holds are remaining as Title-level holds for months because Stanford Libraries has chosen not to recall items from users. Even when we go back to recalling materials, there is a concern that we're allowing renewals to address a super edge-case that would occur in a very narrow time-frame.

**Comment by cbeer** [comment]
Notes from 5/10 story time: https://docs.google.com/document/d/1XooN7BFbzBmf1uGzBvMyH9saoNnPdqvi_e5DuzQIsPo/edit#heading=h.1s6a7tyd0lrj

We're hoping Darsi can find something in Symphony we can use to tell requests that it isn't renewable; otherwise we're looking at retrieving  all the holds for all the checked out items, which seems like a significant performance problem (and mylibrary ends up retrieving a lot of data we'd rather not have..)

**Comment by saseestone** [comment]
@dlrueda is working on a script to add a new Symphony Item Cat5 value of "NORENEW" to items that are checked out with a hold (copy or title level).

Instead of removing the title level hold override (as described above), we'll start looking for the ItemCat5 value = NORENEW  in the charge record and remove those items from renewal eligibility.

**Comment by saseestone** [comment]
@dlrueda script is in production and applying the "NORENEW" value in the ItemCat 5.
