### ISSUE TITLE
Use new blockHistory endpoint

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/mylibrary#660]
https://github.com/sul-dlss/mylibrary/blob/8e1f1ba110b660778ec588636899bda0040f63f7/app/services/symphony_legacy_client.rb#L4

There is now a resource endpoint for blockHistory in web services that we can probably use. Need to evaluate whether group fees are available from it or not.

**Comment by thatbudakguy** [comment]
closing since we're no longer using symphony.
