### ISSUE TITLE
For 11/7/22: Add Aeon to list of links on Requests tab

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/mylibrary#755]
We need to add Aeon to the list of resources that users should check if their request isn't listed in My Account, preferably on 11/7/22.

![image](https://user-images.githubusercontent.com/14897546/198351694-6caa7ec7-a9d5-4de4-b6d6-a85556014d83.png)

It should be the first bullet and read: "Requests for material from Special Collections & University Archives, the David Rumsey Map Center, the Archive of Recorded Sound and East Asia Library Special Collections are listed in Aeon" 

Aeon should be hyperlinked to: https://stanford.aeon.atlas-sys.com/logon

We should also rearrange the bullets in this order:

- Requests for material from Special Collections & University Archives, the David Rumsey Map Center, the Archive of Recorded Sound and East Asia Library Special Collections are listed in [ Aeon](https://stanford.aeon.atlas-sys.com/logon)
- Scan requests are listed in [ Interlibrary Borrowing.](https://sulils.stanford.edu/)
- Requests made through Stanford Libraries Interlibrary Services are listed in [ Interlibrary Borrowing.](https://sulils.stanford.edu/)
- Requests requiring approval are not listed here until they have been approved — typically 1-3 days before your scheduled visit.

All the links out should display the ![image](https://user-images.githubusercontent.com/14897546/198353685-cb5a2dde-a4c9-4d73-9d62-4c57987197da.png) icon (as they do now.)

**Comment by thatbudakguy** [comment]
fyi — this change will go out to prod on Monday 10/31 unless we actively prevent it from doing so. I think that's probably fine, since users can see the info about Aeon requests even if they can't actually make them yet, and it saves us having to remember to do it on 11/7. lmk if that's not the case, though.

**Comment by saseestone** [comment]
I think it's fine.  Worst case scenario is that they create an Aeon account...
