### ISSUE TITLE
For 12/13/22: Replace current BorrowDirect API with new ReShare API for request status.

### ISSUE THREAD

**Issue by corylown** [sul-dlss/mylibrary#757]
Copying @saseestone 's note from the sul-requests issue that's related to this:

> IPLC, the governing body for BorrowDirect, is moving away from Relais to ReShare. We will need to replace our current API with a new ReShare API when routing RecallHold requests to BorrowDirect.

> There is API documentation available in basecamp: https://3.basecamp.com/5319802/buckets/26606684/documents/5132521312
Since it requires a basecamp account, I've copied it here: https://docs.google.com/document/d/1u8NouCFH1DVBV74vNtxv30zp9D0HmQI6yGrCMV9W7Wo/edit#
Hilary Thorsen arranged for my basecamp account, and we can request others through her as needed.

> IPLC plans to cut over from Relais to ReShare on ~~12/1/22~~ OR on ~~12/6/22~~ maybe for real on 12/13/22.

mod-rs API will let us lookup request status. We'll need a **username**, **password**, and **tenant** **(do we need to request these from someone?)**.

**Comment by corylown** [comment]
@cbeer @saseestone I found a way to get reshare requests from the mods-rs API using the patron ID (university id):

```
curl -v --http1.1 -H "X-Okapi-Tenant: $TENANT" -H "X-Okapi-Token: $TOKEN" $OKAPI_URL/rs/patronrequests\?filters=isRequester%3D%3Dtrue\&match=patronIdentifier\&perPage=100\&sort=dateCreated%3Bdesc\&term=patronid
```

Send the request to `$OKAPI_URL/rs/patronrequests` with the following parameters:
- `filters=isRequester%3D%3Dtrue`
- `match=patronIdentifer`
- `perPage={n}`
- `sort=dateCreated%3Bdesc`
- `term={patronid}`

Now I'm trying to figure out the status codes.

**Comment by corylown** [comment]
The human readable request states are [documented here](https://openlibraryfoundation.atlassian.net/wiki/spaces/PR/pages/759365633/States), but there's no mention of the state codes returned by the API.

Aha, maybe this is the right list/mapping of state codes: https://github.com/openlibraryenvironment/stripes-reshare/blob/ef6fb6f5a335b6615935ff60f389003e9ceb6e90/translations/stripes-reshare/en.json#L53

```
  "states.REQ_IDLE": "New",
  "states.REQ_VALIDATED": "Validated",
  "states.REQ_SOURCING_ITEM": "Sourcing",
  "states.REQ_SUPPLIER_IDENTIFIED": "Supplier identified",
  "states.REQ_REQUEST_SENT_TO_SUPPLIER": "Request sent",
  "states.REQ_BORROWER_RETURNED": "Borrower returned item",
  "states.REQ_BORROWING_LIBRARY_RECEIVED": "Awaiting local item creation",
  "states.REQ_CHECKED_IN": "In local circulation process",
  "states.REQ_AWAITING_RETURN_SHIPPING": "Awaiting return shipping",
  "states.REQ_SHIPPED": "Shipped",
  "states.REQ_REQUEST_COMPLETE": "Complete",
  "states.REQ_ERROR": "Error",
  "states.REQ_END_OF_ROTA": "End of rota",
  "states.REQ_INVALID_PATRON": "Invalid patron",
  "states.REQ_EXPECTS_TO_SUPPLY": "Expects to supply",
  "states.REQ_SHIPPED_TO_SUPPLIER": "Return shipped",
  "states.REQ_CONDITIONAL_ANSWER_RECEIVED": "Loan conditions received",
  "states.REQ_CANCEL_PENDING": "Cancel pending",
  "states.REQ_CANCELLED_WITH_SUPPLIER": "Cancelled with previous supplier",
  "states.REQ_CANCELLED": "Cancelled",
  "states.REQ_UNFILLED": "Unfilled",
  "states.REQ_OVERDUE": "Overdue",
  "states.REQ_LOCAL_REVIEW": "Requires review - locally available",
  "states.REQ_FILLED_LOCALLY": "Filled locally",
  "states.REQ_UNABLE_TO_CONTACT_SUPPLIER": "Unable to contact supplier",
```

My understanding is that we really only care about displaying the request from ReShare if it's not yet reached Symphony. I am guessing that the following status code values indicate the request has reached symphony and we should NOT display the request from ReShare:

```
REQ_BORROWER_RETURNED
REQ_CHECKED_IN
REQ_REQUEST_COMPLETE
REQ_SHIPPED_TO_SUPPLIER
REQ_OVERDUE
```

And we also probably only want to display requests that have a status stage of ACTIVE? Maybe there's a way to filter to API query to just ACTIVE requests?

Here's some sample data from a request:

```
response.map { |request| request[:state] }

[{:id=>"89878681-1f93-482e-a50d-c3a37ba1a057",
  :code=>"REQ_EXPECTS_TO_SUPPLY",
  :presSeq=>"0070",
  :owner=>{:id=>"e9849c1e-dd1e-402d-97a6-e11f871ec6d9"},
  :terminal=>false,
  :visible=>true,
  :stage=>"ACTIVE"},
 {:id=>"adf4ca1e-0dbd-460c-a42a-4bfcf1aa4f52",
  :code=>"REQ_END_OF_ROTA",
  :presSeq=>"0080",
  :owner=>{:id=>"e9849c1e-dd1e-402d-97a6-e11f871ec6d9"},
  :terminal=>true,
  :visible=>true,
  :stage=>"COMPLETED"},
 {:id=>"4aab0fc3-f0e7-4a62-ad8f-0dbbbcb190d3",
  :code=>"REQ_CANCELLED",
  :presSeq=>"9998",
  :owner=>{:id=>"e9849c1e-dd1e-402d-97a6-e11f871ec6d9"},
  :terminal=>true,
  :visible=>true,
  :stage=>"COMPLETED"}]
```

**Comment by corylown** [comment]
Still to do:

- [ ] Establish credentials for the application to authenticate to ReShare mod-rs/okapi API
- [ ] Add to shared configs the configuration for enabling ReShare and the API credentials
- [ ] Is fetching the 100 most recent requests enough?
- [ ] Can we limit the fields returned by the API to reduce the data footprint of the response?
- [ ] Tests
- [ ] Error handling for API requests, missing/bad data.

**Comment by saseestone** [comment]
@corylown fetching the most recent 100 requests is fine.
