### ISSUE TITLE
ILLIAD API investigation

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#787]
We may be asked to exclusively use the ILLIAD API to submit ILL requests (replacing our use of BorrowDirect). MyLibrary uses the BorrowDirect API to display request status information to patrons:

- library
- request data
- title
- author
- call number
- date submitted

Determine if ILLIAD's API supports retrieving the same sort of data.

See also #300?

**Comment by corylown** [comment]
Illiad API documentation: https://support.atlas-sys.com/hc/en-us/articles/360011809394-The-ILLiad-Web-Platform-API

The Illiad API appears to provide what we would need to display BorrowDirect and/or other ILL request information in MyLibrary. I've listed some questions below that we would need answered before implementation.

It appears that user-initiated requests in Illiad are made via an account that matches that users SUNET ID. We can make a request to the Illiad API for requests from a particular user:

`https://{ILLIAD_API_URL}/ILLiadWebPlatform/Transaction/UserRequests/{SUNET_ID}`

Example JSON response with a single record (you can also request an XML response):

```
[
   {
        "TransactionNumber": {REQUEST_ID},
        "Username": "{SUNET_ID}",
        "RequestType": "Loan",
        "LoanAuthor": "Wexler, Philip",
        "LoanTitle": "Mystical Sociology: Toward Cosmic Social Theory",
        "LoanPublisher": "Peter Lang",
        "LoanPlace": null,
        "LoanDate": "2013",
        "LoanEdition": null,
        "PhotoJournalTitle": null,
        "PhotoJournalVolume": null,
        "PhotoJournalIssue": null,
        "PhotoJournalMonth": null,
        "PhotoJournalYear": null,
        "PhotoJournalInclusivePages": null,
        "PhotoArticleAuthor": null,
        "PhotoArticleTitle": null,
        "CitedIn": "https://www.worldcat.org/title/844789463?oclcNum=844789463",
        "CitedTitle": null,
        "CitedDate": null,
        "CitedVolume": null,
        "CitedPages": null,
        "NotWantedAfter": "06/11/2023",
        "AcceptNonEnglish": false,
        "AcceptAlternateEdition": true,
        "ArticleExchangeUrl": null,
        "ArticleExchangePassword": null,
        "TransactionStatus": "BorrowDirect Request Sent",
        "TransactionDate": "2023-04-12T14:59:13.883",
        "ISSN": "978-1433123399",
        "ILLNumber": "CST-3516",
        "ESPNumber": "844789463",
        "LendingString": null,
        "BaseFee": null,
        "PerPage": null,
        "Pages": null,
        "DueDate": null,
        "RenewalsAllowed": false,
        "SpecIns": null,
        "Pieces": null,
        "LibraryUseOnly": null,
        "AllowPhotocopies": false,
        "LendingLibrary": null,
        "ReasonForCancellation": null,
        "CallNumber": null,
        "Location": null,
        "Maxcost": null,
        "ProcessType": "Borrowing",
        "ItemNumber": null,
        "LenderAddressNumber": null,
        "Ariel": false,
        "Patron": null,
        "PhotoItemAuthor": null,
        "PhotoItemPlace": null,
        "PhotoItemPublisher": null,
        "PhotoItemEdition": null,
        "DocumentType": "Book",
        "InternalAcctNo": null,
        "PriorityShipping": null,
        "Rush": null,
        "CopyrightAlreadyPaid": "No",
        "WantedBy": null,
        "SystemID": "Reshare:stanford",
        "ReplacementPages": null,
        "IFMCost": null,
        "CopyrightPaymentMethod": null,
        "ShippingOptions": null,
        "CCCNumber": null,
        "IntlShippingOptions": null,
        "ShippingAcctNo": null,
        "ReferenceNumber": null,
        "CopyrightComp": null,
        "TAddress": null,
        "TAddress2": null,
        "TCity": null,
        "TState": null,
        "TZip": null,
        "TCountry": null,
        "TFax": null,
        "TEMailAddress": null,
        "TNumber": null,
        "HandleWithCare": false,
        "CopyWithCare": false,
        "RestrictedUse": false,
        "ReceivedVia": null,
        "CancellationCode": null,
        "BillingCategory": null,
        "CCSelected": "No",
        "OriginalTN": null,
        "OriginalNVTGC": null,
        "InProcessDate": null,
        "InvoiceNumber": null,
        "BorrowerTN": null,
        "WebRequestForm": "LoanRequest",
        "TName": null,
        "TAddress3": null,
        "IFMPaid": null,
        "BillingAmount": null,
        "ConnectorErrorStatus": null,
        "BorrowerNVTGC": null,
        "CCCOrder": null,
        "ShippingDetail": null,
        "ISOStatus": null,
        "OdysseyErrorStatus": null,
        "WorldCatLCNumber": null,
        "Locations": null,
        "FlagType": null,
        "FlagNote": null,
        "CreationDate": "2023-04-12T14:55:14.097",
        "ItemInfo1": "Yes",
        "ItemInfo2": null,
        "ItemInfo3": "E Version Acceptable",
        "ItemInfo4": "GREEN",
        "ItemInfo5": null,
        "SpecialService": null,
        "DeliveryMethod": null,
        "Web": null,
        "PMID": null,
        "DOI": null,
        "LastOverdueNoticeSent": null,
        "ExternalRequest": null
    }
]
```

How the request information displayed in MyLibrary could map to the Illiad API response:

- **Deliver to:** Stanford (hard coded) or `ItemInfo4` (has library code e.g. GREEN)
- **Not needed after:** in transit (hard coded) or `NotWantedAfter`
- **Title:** `LoanTitle`
- **Author:** `LoanAuthor`
- **Requested:** `CreationDate` or `TransactionDate`
- **Source:** BorrowDirect (hard coded) or `SystemID` (has values like `Reshare:stanford`)
- **Call Number:** `CallNumber` (mostly this is unpopulated for Borrow Direct requests that I found)

**Implementation questions:**

1. What are the possible values of TransactionStatus? And do we only want to display request information for requests that have particular statuses. Relates to https://github.com/sul-dlss/mylibrary/issues/300
2. Do we want to display all kinds of Iliad transactions or only Borrow direct ones? And if we only want to display BorrowDirect requests how do we select/filter to these requests?
3. Do we want to display richer/more dynamic information than we do with BorrowDirect? See options above for hard-coded values like we have currently, vs. information present in the Illiad request response that we might choose to display instead.

**Filtering the API requests:**

It's likely we will want to filter responses based on particular request characteristics. Documentation on how to filter the response: https://support.atlas-sys.com/hc/en-us/articles/360011809394-The-ILLiad-Web-Platform-API#h_01FCP7WXK3SYH7ABXJE1RXTVJN

Example of a filter applied to an API request:

`/ILLiadWebPlatform/Transaction/UserRequests/jdoe?$filter=TransactionStatus eq 'Request Sent`

**Comment by cbeer** [comment]
> 1. [...] And do we only want to display request information for requests that have particular statuses.

We should show requests that have yet to arrive at SUL. Once we have the book, it turns into an item in Symphony (and presumably FOLIO?) with normal display

> 2.   Do we want to display all kinds of Iliad transactions or only Borrow direct ones?

All request type should be fine.

> 3. Do we want to display richer/more dynamic information than we do with BorrowDirect? S

Let's plan on parity to start :shrug:

--

Once we have the list of statuses, we can close this and open some implementation tickets.

**Comment by corylown** [comment]
@saseestone I think we need to know what `TransactionStatus` values translate to requests that have been created but are not yet received in Symphony/FOLIO.

**Comment by cbeer** [comment]
Started building out #300 with this information.
