### ISSUE TITLE
Hook up holds display + functionality in mylibrary

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#827]
TODO:
- [x] `patron_key` (does FOLIO even have a notion of holds for a proxy?)
- [x] `queue_length` 
- [x]  borrowing limit (https://github.com/sul-dlss/folio-graphql/issues/33)
- [x] `from_borrow_direct?`/  `from_ill` (#833)
- [x] stub out CDL stuff so that nothing errors; deferring CDL until after launch

Verify we can:

- [x] cancel a hold (#829)
- [ ] change the pickup library (https://github.com/sul-dlss/mylibrary/pull/840)

**Comment by marlo-longley** [comment]
There is a draft PR for "change the pickup library" at #840 
Waiting for further work on this until we know more about whether the data from the service-points.json (API response) has data we can use, specifically around staff-only pickup locations. But the verification that we can use FOLIO to change a pickup location is complete -- this works in the UI.

**Comment by marlo-longley** [comment]
I just spent a while looking into the `queue_length` property. I couldn't find anything in the FOLIO docs for getting the total queue length. Is it possible we could ship with just the waitlist position? If I am #8 on the waitlist, do I care if I am #8 out of 20? We have the ability to get that the queuePosition is 8.

**Comment by cbeer** [comment]
My memory is... patrons want to be aware that there's other requests after them (because they'll get a reduced checkout period).

**Comment by marlo-longley** [comment]
Gotcha. 

It's possible we could get all the open request for the requested item and add them up, something along the lines of: `circulation/requests?item=#{item_id}&status=open` -- but there isn't a direct endpoint related to the request, from what I can tell

**Comment by marlo-longley** [comment]
I found some quite old documentation that made reference to `circulation/requests/#{request_id}/positions`, where then you could add up all the positions, but that endpoint doesn't work for me on our FOLIO / doesn't exist anymore?

**Comment by marlo-longley** [comment]
Re proxy users placing holds. From the FOLIO docs on adding a Proxy:
https://docs.folio.org/docs/users/#add-a-proxy
> Optional: Select whether the Proxy can request for the sponsor. If you select Yes, then the proxy can place requests for materials on behalf of the sponsor.

It seems like yes, proxies can place requests.

**Comment by saseestone** [comment]
> It's possible we could get all the open requests for the requested item and add them up, something along the lines of: `circulation/requests?item=#{item_id}` and filter for open status -- but there isn't a direct endpoint related to the request, from what I can tell

Another aspect of showing the "Waitlist position" (i.e. queue number) was to give the user a sense of where they were in the queue (e.g. "oh, I'm the 17th person in line for Harry's book so I shouldn't expect to get it for at least 3 months.") If we show a simple "there are 7 open requests for this item, we're not really getting at their particular number in that list of 7. 

That said, it's always been a little "you're number 7 right now, but that could change" because if the user was a fee borrower, other requesters could jump ahead of them in the queue. 

IF we can't relate the queue number related to their request, I wonder if there is value to displaying the Waitlist number. I can see some value, but we'd need a different label and text (not "1 of 1")

**Comment by marlo-longley** [comment]
Hey @saseestone . We currently have access to the waitlist position, so "Queue position 4" and are working on getting the second have of that, the overall queue length, so "Queue position 4 of 20 total requests". It seems possible.

**Comment by marlo-longley** [comment]
Research into borrowing limit and blocks reference here: https://github.com/sul-dlss/sul-requests/issues/1460

**Comment by marlo-longley** [comment]
We decided to break out the pickup locations/Service Points work into a fresh ticket: #875 
This can now be considered done!
