### ISSUE TITLE
Hook up fees and fines display

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#830]
Building on https://github.com/sul-dlss/mylibrary/pull/828:

- [x] Translations of FOLIO feeFineTypes into patron-visible labels
~~`sequence` (used to... figure out if the patron recently paid?)~~ broken out into https://github.com/sul-dlss/mylibrary/issues/832
- [x] is `owed` the right field? fixture fines didn't seem to have it
- [x] is `dateCreated` the right field to replace `billDate`? fixture fines didn't seem to have that populated
- [x] should there be an `itemId` attached to fees + fines? the API docs say it's required, but the fixtures didn't seem to have it

**Comment by thatbudakguy** [comment]
there may be fee/fine types in FOLIO that are (always) missing data that we would otherwise expect to have; might be UX implications for handling this

**Comment by marlo-longley** [comment]
re the presence of `itemId` being required. There are currently 3 users with fees:
- undergrad1 and blocked1 have fees with associated barcodes. `itemId` is returned from the API. 
- faculty1 has a fee without a barcode. `itemId` is null. Seemingly this didn't cause problems when creating the record in the UI, but the API throws errors:


![Image](https://github.com/sul-dlss/mylibrary/assets/1328900/841bb877-51f6-41c7-8815-45a0553ed773)

 

![Image](https://github.com/sul-dlss/mylibrary/assets/1328900/059771a9-a7fc-41a0-b11e-0e2e5ea1b055)

**Comment by marlo-longley** [comment]
Re: "translation of FeeFineTypes to patron visible labels" -- These are the current labels we get. They seem OK. @saseestone , do these need editing or changing in any way?

`{
  "data": {
    "feeFineTypes": [
      {
        "id": "9523cb96-e752-40c2-89da-60f3961a488d",
        "feeFineType": "Overdue fine",
      },
      {
        "id": "d20df2fb-45fd-4184-b238-0d25747ffdd9",
        "feeFineType": "Replacement processing fee"
      },
      {
        "id": "cf238f9f-7018-47b7-b815-bb2db798e19f",
        "feeFineType": "Lost item fee",
      },
      {
        "id": "c7dede15-aa48-45ed-860b-f996540180e0",
        "feeFineType": "Lost item processing fee",
      },
      {
        "id": "73785370-d3bd-4d92-942d-ae2268e02ded",
        "feeFineType": "Lost item fee (actual cost)",
      },
      {
        "id": "b694177e-6983-4dc8-9f40-c63558ec1a14",
        "feeFineType": "Manual Replacement Fee",
      },
      {
        "id": "2303771a-e28e-4fc7-b110-738746b56ebd",
        "feeFineType": "Manual Replacement Fee",
      },
      {
        "id": "2769c09d-c2e8-4a40-9601-48f95a14a395",
        "feeFineType": "damage to material",
      },
      {
        "id": "116f8665-4ba5-4c14-8c0e-36c41e961381",
        "feeFineType": "lost item",
      },
      {
        "id": "d90d6659-2ed4-41ba-a23e-8e29e9d632e7",
        "feeFineType": "short term fine",
      }
    ]
  }
}`

**Comment by saseestone** [comment]
I found in the FOLIO app settings where these feeFineTypes are set. One thing to note is that in the FOLIO UI, administrators can create Fee/fine types by "Fee/fine owners". So there is a different list for Business, Law, Hoover, Lane and SUL. That's why you're seeing duplicates.

I'll trace if/why it's important to have different lists by Tenant. Regardless, we should be fine to use the label you get for "feeFineType", and I will work with FOLIO administrators to have that name/label be user-friendly.

**Comment by marlo-longley** [comment]
Perfect, thank you @saseestone !

**Comment by marlo-longley** [comment]
Re the last checkbox about `itemId`, we are able to get the id of the fined item via account > item > id (not "itemId).
