### ISSUE TITLE
Hook up the ability to pay fees + fines

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#831]
Pair with Josh to figure out the right approach for interacting with the payment provider + FOLIO

**Comment by thatbudakguy** [comment]
Josh might be working on this already? Need to connect to figure out where to start.

**Comment by jcoyne** [comment]
WIP: https://github.com/sul-dlss/mylibrary/tree/cybersource-payments

**Comment by jgreben** [comment]
I pulled in the latest from mylibrary origin/main but all of my tests are failing when I use 
```
ils:
  client: FolioClient
  patron_model: Folio::Patron
```
 in the test config

**Comment by cbeer** [comment]
@thatbudakguy : Fixed?

**Comment by thatbudakguy** [comment]
you mean re: @jgreben's comment above? doesn't happen for me or in CI 🤷🏻‍♂️ 

the tests for this issue mock/set the client and patron models on their own anyway, so settings shouldn't have any effect.

**Comment by cbeer** [comment]
I mean, was this ticket addressed by #901?

**Comment by jgreben** [comment]
Yes my comment last month was about my local branch failing tests, but @thatbudakguy refactored all that in https://github.com/sul-dlss/mylibrary/pull/901. Closing.
