### ISSUE TITLE
Display billing transaction history for a patron

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#832]
From `Symphony::Payment`:
- [x] `key` (billNumber)
- [x] `bill_description` / `nice_bill_description`
- [x] `bill_amount`
- [x] `bill_date`
- [x] `item_title`
- [x] `item_library`
- [x] `payment_amount`
- [x] `payment_date`
- [x] `resolution`
- [x] `paid_fee?`

**Comment by jcoyne** [comment]
Depends on https://github.com/sul-dlss/folio-graphql/pull/90

**Comment by thatbudakguy** [comment]
what it looks like in mylibrary-dev (non-FOLIO) for UNDERGRAD1:

![Screenshot 2023-07-17 at 10 10 44](https://github.com/sul-dlss/mylibrary/assets/4924494/d7508393-5d0b-42b9-9aea-1d70e599ef46)
