### ISSUE TITLE
How do we know if an item is from ILL/ILB/BorrowDirect/etc?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#833]

**Comment by saseestone** [comment]
Asked Hilary in Resource Sharing about this. She wasn't sure, but promised to provide us some exemplar records soon (i.e. next week)

**Comment by thatbudakguy** [comment]
we know we have some of these (lots, actually) in folio-test, but they're suppressed from discovery and not loaned out currently. @saseestone to work on the data some more

**Comment by saseestone** [comment]
So the "lots of these in folio-test" are migrated items that Darsi brought over from Symphony into folio-test. Luckily, she didn't migrate the loans or holds on these records, so in theory, I can commandeer some for our testing.

When I tried to create checkouts and requests, I'm getting a "no loan policy" message so we've asked the circ folks to create the correct circrules for these items.

**Comment by marlo-longley** [comment]
Thanks for looking into it @saseestone !

**Comment by saseestone** [comment]
Ok checkouts and pages created on migrated borrowdirect inventory items. Users are undergrad1 (page that is ready for pickup) and faculty1 (one checkout, one page ready for pickup).

**Comment by marlo-longley** [comment]
We can use location codes within `effectiveLocation`. Here is an example of data returned in folio-graphql for a hold placed on a BorrowDirect item:

``` json    
     {
        "details": {
          "itemId": "2a47e79d-12e7-5f62-ab96-c3e85a864546",
          "instanceId": "edcdba3e-0d4f-5b3e-9e0e-37f5c2ecbad8",
          "tags": null
        },
        "item": {
          "item": {
            "effectiveLocation": {
              "code": "SUL-BORROW-DIRECT",
              "description": null,
              "name": "SUL Borrow Direct"
            }
          },
          "instance": {
            "id": "edcdba3e-0d4f-5b3e-9e0e-37f5c2ecbad8"
          }
        }
      }
```
So in this case, we have `SUL-BORROW-DIRECT` as the effectiveLocation code.
Currently there are no codes for ILL or ILB. But we can use this same approach when those codes are created.

With [this PR](https://github.com/sul-dlss/mylibrary/pull/863), we will have that info available for both holds and loans (was already retrieved as part of the loan info).
