### ISSUE TITLE
Do we need to record fillByDate in FOLIO?

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#834]

**Comment by thatbudakguy** [comment]
symphony holds have a "fill by date". it's not super clear what that does. FOLIO doesn't have it. does that matter? do we still need it?

**Comment by saseestone** [comment]
The fillbydate in Symphony corresponds to the "Not needed after" field in our request forms. 

In FOLIO this should correspond to "Request expiration date". Here's what it looks like in the FOLIO UI:


![Image](https://github.com/sul-dlss/mylibrary/assets/14897546/c3288c9d-94ee-4a29-acc7-bf9a13f4b4e2)

**Comment by cbeer** [comment]
I think FOLIO has two different expiration dates ("holdShelfExpirationDate" and "requestExpirationDate") and mylibrary has two different fields ("Fill by date" and "Expiration date").

Is our "Fill by date" actually the  requestExpirationDate, and our expiration date the "holdShelfExpirationDate"?
