### ISSUE TITLE
Implement from_ill? and from_ilb? for Folio::Checkout

### ISSUE THREAD

**Issue by corylown** [sul-dlss/mylibrary#862]
We have already implemented [Folio::Checkout.from_borrow_direct?](https://github.com/sul-dlss/mylibrary/blob/main/app/models/folio/checkout.rb#L219), but do not yet have examples of ILL records in FOLIO that are not from BorrowDirect.

Blocked by https://github.com/sul-dlss/mylibrary/issues/833

**Comment by thatbudakguy** [comment]
The plan is to use locations to differentiate these.

**Comment by marlo-longley** [comment]
Since #833 is no longer blocked can we move this to Ready?

**Comment by thatbudakguy** [comment]
@marlo-longley at planning we found out that this will be blocked until after launch, because we won't know the real names of the ILL/ILB locations until they get decided. so unfortunately it isn't ready.

**Comment by cbeer** [comment]
Why don't we implement the functionality (using the `SUL-BORROW-DIRECT` location we assumed in #833)? It feels like we can at least do the functional implementation and populate the right data later.

It seems like if it's a location, we might add this property to location/details and let the location creators handle it post-launch, but our code would be ready.

**Comment by marlo-longley** [comment]
@cbeer I had a similar thought and created https://github.com/sul-dlss/mylibrary/pull/869
I didn't know how to test it, thought.

**Comment by cbeer** [comment]
Don't we have some migrated borrow direct items in -test already?
<img width="239" alt="Screenshot 2023-07-05 at 10 03 47" src="https://github.com/sul-dlss/mylibrary/assets/111218/8501303a-5f0f-49a3-bcf3-14c2ef1101ab">

https://folio-test.stanford.edu/inventory?filters=effectiveLocation.08601677-5d55-459d-a499-b06114c940c2&segment=items&sort=title

**Comment by corylown** [comment]
@cbeer I'm no longer sure what this issue is asking for. We've already wired up `from_ill?` for checkouts and requests using the `SUL-BORROW-DIRECT` code. What's left is handling `from_ilb?` but we don't know what the location will be yet. Are you suggesting we implement `from_ilb?` using a dummy code and replace that code once we know it? Something else? When I wrote this I intended it to capture minor work needed after we know the the ilb location code will be in FOLIO.

**Comment by cbeer** [comment]
I think we established non-borrow-direct ILB will use some location code, so we should be able to write the code with a placeholder value... 

If that's too much, we should at least stub out the existing `Folio::Checkout#from_ilb?` (copy/pasted from Symphony's code?) so it doesn't look half complete.
