### ISSUE TITLE
Use FOLIO Service Points for request pickup locations

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/mylibrary#875]
A Draft PR started here https://github.com/sul-dlss/mylibrary/pull/840 but this was before all the Service Points work so it may need to be thrown out. This ticket pulled out from #827.

What needs to change are the options we currently see when trying to modify a request:

![Screenshot 2023-07-14 at 13 01 08](https://github.com/sul-dlss/mylibrary/assets/1328900/9aa87f74-46c6-4376-af7c-ade974073b2d)

**Comment by cbeer** [comment]
The list of pickup locations should be the same as the list when you initially place the request:
https://github.com/sul-dlss/sul-requests/blob/main/app/models/folio/request_abilities.rb#L74-L80

(e.g. using the location's `pageServicePoints`, service point's `isDefaultPickup`, etc)
