### ISSUE TITLE
Add a splash page to mylibrary (as needed) to explain to patrons why the app is down

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/mylibrary#894]
we're going to replace the text on the existing page we show when Symphony is down each day at 4am.
it replaces the root page, but doesn't do anything super smart to redirect people if they happen to use a deep link and try to visit their checkouts, etc. and that's fine.

**Comment by thatbudakguy** [comment]
@saseestone working on text

**Comment by saseestone** [comment]
Can you point me to what it says now? (Sorry - not going to stay up/wake up to find out...)

Basically we need to say:
My Library Account will be unavailable August 19 through August 27 for to a major system upgrade.  Please contact greencirc@stanford.edu if you have an urgent concern about your library account. 

[More information about available services during the upgrade](https://library.stanford.edu/news/major-system-upgrade-august-19-27)

**Comment by jcoyne** [comment]
@saseestone I believe it is https://github.com/sul-dlss/mylibrary/blob/5207a4f7304f966c89a4a37548401131659fc1b1/app/views/shared/_unavailable.html.erb#L1

**Comment by cbeer** [comment]
Now that morison is down, here's the current page on -dev:

![Screenshot 2023-08-04 at 08 05 05](https://github.com/sul-dlss/mylibrary/assets/111218/ec5e32c3-3577-4f30-80fa-5b6ac0659ac6)
