### ISSUE TITLE
Remove oracle support

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#913]
Remove `oci8` gem and any code directly querying the Symphony Oracle database:
- [x] https://github.com/sul-dlss/mylibrary/pull/916

Also, remove oracle system packages from puppet and uninstall them.

- [x] dev: https://github.com/sul-dlss/puppet/pull/9792
- [x] uat: https://github.com/sul-dlss/puppet/pull/9794
- [x] prod:

**Comment by jcoyne** [comment]
<img src="https://i.giphy.com/media/l0ExjbToOj4n23OmY/giphy.webp">
