### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for user_id: c4a201e8-36df-45a0-bd0d-508b4187bcea, item_id: e9c292da-0829-4166-9e60-596b928f0155 was not successful. status: 422, {
  "errors" : [ {
    "message" : "item is not loanable",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "No loan"
    }, {
      "key" : "loanPolicyId",
      "value" : "34ea18bb-f71f-4f22-85b3-71b981d57db2"
    } ],
    "overridableBlock" : {
      "name" : "renewalDueDateRequiredBlock",
      "mi...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#930]
## Backtrace

    line 237 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 107 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_request
    line 84 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/99761471)

**Comment by cbeer** [comment]
This failure is weird on two levels:

- a) that this item was included as part of "renew all"; it was just loaned and is probably too soon to renew?
- b) we're probably assuming if you've checked a thing out, it is still loanable... and that's apparently not the case.

**Comment by cbeer** [comment]
The due date issue is a FOLIO bug around loan policies. This is a fixed schedule loan that should be due on 7/1, but the Law library is closed for July 4th... and even though the loan policy seems like it means "next open business day", it picked an earlier date.

**Comment by corylown** [comment]
b) I added a rescue block around the `check_response` to allow the failed renewal responses to get the controller where they're handled in the UI. There are some other things we could opt to do:

- Fetch the item in its current state and resolve its current loan-policy to make sure we're assessing renewability with current information. This is is potentially slow...
- There are some item statuses that are not eligible for renewal (aged to lost, declared lost, claimed returned). We could check for these, but again we'd need to fetch each item and check.

**Comment by corylown** [comment]
The remaining errors are all related to the loan policy changing after the loan -- either the item is no longer eligible for lending or it's allowed number of renewals was reduced. In both cases the information on the loan is not updated to reflect the current loan policy.

**Comment by corylown** [comment]
I'm calling this done and will pick up the remaining loan policy change issue in #961
