### ISSUE TITLE
Design for contact access services for anonymous users

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#94]
When a user is not logged in we will not have their name and email address, so should they be able to contact Access Services, and if so, what should the flash message be when they submit the form:
- in the case of a logged-in user?
- in the case of a non-logged-in user?

**Comment by jgreben** [comment]
Currently:
<img width="495" alt="Screen Shot 2019-07-12 at 10 27 10 AM" src="https://user-images.githubusercontent.com/3093850/61146840-d148d280-a48f-11e9-855d-26e18ebc1645.png">
<img width="496" alt="Screen Shot 2019-07-12 at 10 27 29 AM" src="https://user-images.githubusercontent.com/3093850/61146841-d148d280-a48f-11e9-8022-e439dcab00ae.png">
<img width="496" alt="Screen Shot 2019-07-12 at 10 27 58 AM" src="https://user-images.githubusercontent.com/3093850/61146842-d148d280-a48f-11e9-90eb-faf13ee21172.png">

**Comment by jvine** [comment]
After discussion with @saseestone, we've arrived at this:  Remove the contact links from the header on the login screen. The contact links (email and phone) appear only after the user is logged in. 

The intent of the header links is to allow users to directly ask questions about their account status. Users who aren't logged in yet could be anyone in the world; anonymous emails are not acceptable. It's likely more appropriate for someone who is not able to login or has questions about getting access to the libraries to contact the libraries through the Feedback form. We may also add a link to access and contact information on the website to the section below the login buttons.
