### ISSUE TITLE
Add "Expired" patron standing and implement "no access" labels

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/mylibrary#95]
@jvine @saseestone What should a user with expired privileges see when they log into the app? Should they be denied access or do they login, see a summary page with a specific status?

**Comment by saseestone** [comment]
we discussed this on the call, but to document: 

Users with expired privileges should see their full account with summary page.  We discussed having an additional "status" = expired.

**Comment by jvine** [comment]
Something like this? 

<img width="375" alt="Screen Shot 2019-07-12 at 4 12 33 PM" src="https://user-images.githubusercontent.com/6945691/61162948-e3426980-a4bf-11e9-8dcd-733ac2aa8e03.png">

Though I suppose it's possible to have expired privileges and still have some items out/fines due.

**Comment by cbeer** [comment]
Is there an expired fixture user?

**Comment by saseestone** [comment]
Just created one:

Library ID: EXPIRED
PIN: EXPIRED

And I added it to the Test User doc.

**Comment by jkeck** [comment]
Can a group be "Expired"?

**Comment by cbeer** [comment]
No, groups don't expire (and/or if they did, we don't get that information).

**Comment by saseestone** [comment]
They definitely don't expire.  Proxy user accounts that are associated with groups expire - the the group itself does not expire.

**Comment by cbeer** [comment]
I'm bringing this back for a quick question.. can expired users renew material, change/cancel requests, or pay fines?

**Comment by shelleydoljack** [comment]
Expired users means that their privileges have expired. I think all they should be able to do is pay fines.
