### ISSUE TITLE
[mylibrary/prod] FolioClient::IlsError: Renew request for user_id: 2ce1a5eb-8fe4-4487-acd5-5e8ea6901bf6, item_id: 816a1fe2-3661-570d-a1b7-30ff67110a77 was not successful. status: 422, {
  "errors" : [ {
    "message" : "loan at maximum renewal number",
    "parameters" : [ {
      "key" : "loanPolicyName",
      "value" : "1yearfixed-2renew-7daygrace"
    }, {
      "key" : "loanPolicyId",
      "value" : "ad47ac4d-8305-4039-8ac4-93a69a789074"
    } ],
    "overridableBlock" : {
      "name" : "renewalBl...

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/mylibrary#961]
## Backtrace

    line 256 of [PROJECT_ROOT]/app/services/folio_client.rb: check_response
    line 113 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item_request
    line 89 of [PROJECT_ROOT]/app/services/folio_client.rb: renew_item

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/62116/faults/100509416)

**Comment by corylown** [comment]
The loan policy on this item changed from `1qtr-3renew-7daygrace` when it was checked out to `1yearfixed-2renew-7daygrace`. This patron already has 2 renewals. I can see how much of a performance hit it is to lookup the latest loan policy for each checked out item.
